/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ContainerContainerPushRepositoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerContainerPushRepositoryResponse{}

// ContainerContainerPushRepositoryResponse Serializer for Container Push Repositories.
type ContainerContainerPushRepositoryResponse struct {
	// The Pulp Resource Name (PRN).
	Prn *string `json:"prn,omitempty"`
	// A reference to an associated signing service.
	ManifestSigningService *string `json:"manifest_signing_service,omitempty"`
	LatestVersionHref *string `json:"latest_version_href,omitempty"`
	VersionsHref *string `json:"versions_href,omitempty"`
	// Timestamp of creation.
	PulpCreated *time.Time `json:"pulp_created,omitempty"`
	// Retain X versions of the repository. Default is null which retains all versions.
	RetainRepoVersions *int64 `json:"retain_repo_versions,omitempty"`
	PulpHref *string `json:"pulp_href,omitempty"`
	// A unique name for this repository.
	Name string `json:"name"`
	// An optional description.
	Description *string `json:"description,omitempty"`
	// Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.
	PulpLastUpdated *time.Time `json:"pulp_last_updated,omitempty"`
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
}

type _ContainerContainerPushRepositoryResponse ContainerContainerPushRepositoryResponse

// NewContainerContainerPushRepositoryResponse instantiates a new ContainerContainerPushRepositoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerContainerPushRepositoryResponse(name string) *ContainerContainerPushRepositoryResponse {
	this := ContainerContainerPushRepositoryResponse{}
	this.Name = name
	return &this
}

// NewContainerContainerPushRepositoryResponseWithDefaults instantiates a new ContainerContainerPushRepositoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerContainerPushRepositoryResponseWithDefaults() *ContainerContainerPushRepositoryResponse {
	this := ContainerContainerPushRepositoryResponse{}
	return &this
}

// GetPrn returns the Prn field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetPrn() string {
	if o == nil || IsNil(o.Prn) {
		var ret string
		return ret
	}
	return *o.Prn
}

// GetPrnOk returns a tuple with the Prn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetPrnOk() (*string, bool) {
	if o == nil || IsNil(o.Prn) {
		return nil, false
	}
	return o.Prn, true
}

// HasPrn returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasPrn() bool {
	if o != nil && !IsNil(o.Prn) {
		return true
	}

	return false
}

// SetPrn gets a reference to the given string and assigns it to the Prn field.
func (o *ContainerContainerPushRepositoryResponse) SetPrn(v string) {
	o.Prn = &v
}

// GetManifestSigningService returns the ManifestSigningService field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetManifestSigningService() string {
	if o == nil || IsNil(o.ManifestSigningService) {
		var ret string
		return ret
	}
	return *o.ManifestSigningService
}

// GetManifestSigningServiceOk returns a tuple with the ManifestSigningService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetManifestSigningServiceOk() (*string, bool) {
	if o == nil || IsNil(o.ManifestSigningService) {
		return nil, false
	}
	return o.ManifestSigningService, true
}

// HasManifestSigningService returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasManifestSigningService() bool {
	if o != nil && !IsNil(o.ManifestSigningService) {
		return true
	}

	return false
}

// SetManifestSigningService gets a reference to the given string and assigns it to the ManifestSigningService field.
func (o *ContainerContainerPushRepositoryResponse) SetManifestSigningService(v string) {
	o.ManifestSigningService = &v
}

// GetLatestVersionHref returns the LatestVersionHref field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetLatestVersionHref() string {
	if o == nil || IsNil(o.LatestVersionHref) {
		var ret string
		return ret
	}
	return *o.LatestVersionHref
}

// GetLatestVersionHrefOk returns a tuple with the LatestVersionHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetLatestVersionHrefOk() (*string, bool) {
	if o == nil || IsNil(o.LatestVersionHref) {
		return nil, false
	}
	return o.LatestVersionHref, true
}

// HasLatestVersionHref returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasLatestVersionHref() bool {
	if o != nil && !IsNil(o.LatestVersionHref) {
		return true
	}

	return false
}

// SetLatestVersionHref gets a reference to the given string and assigns it to the LatestVersionHref field.
func (o *ContainerContainerPushRepositoryResponse) SetLatestVersionHref(v string) {
	o.LatestVersionHref = &v
}

// GetVersionsHref returns the VersionsHref field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetVersionsHref() string {
	if o == nil || IsNil(o.VersionsHref) {
		var ret string
		return ret
	}
	return *o.VersionsHref
}

// GetVersionsHrefOk returns a tuple with the VersionsHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetVersionsHrefOk() (*string, bool) {
	if o == nil || IsNil(o.VersionsHref) {
		return nil, false
	}
	return o.VersionsHref, true
}

// HasVersionsHref returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasVersionsHref() bool {
	if o != nil && !IsNil(o.VersionsHref) {
		return true
	}

	return false
}

// SetVersionsHref gets a reference to the given string and assigns it to the VersionsHref field.
func (o *ContainerContainerPushRepositoryResponse) SetVersionsHref(v string) {
	o.VersionsHref = &v
}

// GetPulpCreated returns the PulpCreated field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetPulpCreated() time.Time {
	if o == nil || IsNil(o.PulpCreated) {
		var ret time.Time
		return ret
	}
	return *o.PulpCreated
}

// GetPulpCreatedOk returns a tuple with the PulpCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetPulpCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpCreated) {
		return nil, false
	}
	return o.PulpCreated, true
}

// HasPulpCreated returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasPulpCreated() bool {
	if o != nil && !IsNil(o.PulpCreated) {
		return true
	}

	return false
}

// SetPulpCreated gets a reference to the given time.Time and assigns it to the PulpCreated field.
func (o *ContainerContainerPushRepositoryResponse) SetPulpCreated(v time.Time) {
	o.PulpCreated = &v
}

// GetRetainRepoVersions returns the RetainRepoVersions field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetRetainRepoVersions() int64 {
	if o == nil || IsNil(o.RetainRepoVersions) {
		var ret int64
		return ret
	}
	return *o.RetainRepoVersions
}

// GetRetainRepoVersionsOk returns a tuple with the RetainRepoVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetRetainRepoVersionsOk() (*int64, bool) {
	if o == nil || IsNil(o.RetainRepoVersions) {
		return nil, false
	}
	return o.RetainRepoVersions, true
}

// HasRetainRepoVersions returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasRetainRepoVersions() bool {
	if o != nil && !IsNil(o.RetainRepoVersions) {
		return true
	}

	return false
}

// SetRetainRepoVersions gets a reference to the given int64 and assigns it to the RetainRepoVersions field.
func (o *ContainerContainerPushRepositoryResponse) SetRetainRepoVersions(v int64) {
	o.RetainRepoVersions = &v
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetPulpHref() string {
	if o == nil || IsNil(o.PulpHref) {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || IsNil(o.PulpHref) {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasPulpHref() bool {
	if o != nil && !IsNil(o.PulpHref) {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *ContainerContainerPushRepositoryResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetName returns the Name field value
func (o *ContainerContainerPushRepositoryResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContainerContainerPushRepositoryResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ContainerContainerPushRepositoryResponse) SetDescription(v string) {
	o.Description = &v
}

// GetPulpLastUpdated returns the PulpLastUpdated field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetPulpLastUpdated() time.Time {
	if o == nil || IsNil(o.PulpLastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.PulpLastUpdated
}

// GetPulpLastUpdatedOk returns a tuple with the PulpLastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetPulpLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpLastUpdated) {
		return nil, false
	}
	return o.PulpLastUpdated, true
}

// HasPulpLastUpdated returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasPulpLastUpdated() bool {
	if o != nil && !IsNil(o.PulpLastUpdated) {
		return true
	}

	return false
}

// SetPulpLastUpdated gets a reference to the given time.Time and assigns it to the PulpLastUpdated field.
func (o *ContainerContainerPushRepositoryResponse) SetPulpLastUpdated(v time.Time) {
	o.PulpLastUpdated = &v
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *ContainerContainerPushRepositoryResponse) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerPushRepositoryResponse) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *ContainerContainerPushRepositoryResponse) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *ContainerContainerPushRepositoryResponse) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

func (o ContainerContainerPushRepositoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerContainerPushRepositoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prn) {
		toSerialize["prn"] = o.Prn
	}
	if !IsNil(o.ManifestSigningService) {
		toSerialize["manifest_signing_service"] = o.ManifestSigningService
	}
	if !IsNil(o.LatestVersionHref) {
		toSerialize["latest_version_href"] = o.LatestVersionHref
	}
	if !IsNil(o.VersionsHref) {
		toSerialize["versions_href"] = o.VersionsHref
	}
	if !IsNil(o.PulpCreated) {
		toSerialize["pulp_created"] = o.PulpCreated
	}
	if !IsNil(o.RetainRepoVersions) {
		toSerialize["retain_repo_versions"] = o.RetainRepoVersions
	}
	if !IsNil(o.PulpHref) {
		toSerialize["pulp_href"] = o.PulpHref
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.PulpLastUpdated) {
		toSerialize["pulp_last_updated"] = o.PulpLastUpdated
	}
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	return toSerialize, nil
}

func (o *ContainerContainerPushRepositoryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerContainerPushRepositoryResponse := _ContainerContainerPushRepositoryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerContainerPushRepositoryResponse)

	if err != nil {
		return err
	}

	*o = ContainerContainerPushRepositoryResponse(varContainerContainerPushRepositoryResponse)

	return err
}

type NullableContainerContainerPushRepositoryResponse struct {
	value *ContainerContainerPushRepositoryResponse
	isSet bool
}

func (v NullableContainerContainerPushRepositoryResponse) Get() *ContainerContainerPushRepositoryResponse {
	return v.value
}

func (v *NullableContainerContainerPushRepositoryResponse) Set(val *ContainerContainerPushRepositoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerContainerPushRepositoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerContainerPushRepositoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerContainerPushRepositoryResponse(val *ContainerContainerPushRepositoryResponse) *NullableContainerContainerPushRepositoryResponse {
	return &NullableContainerContainerPushRepositoryResponse{value: val, isSet: true}
}

func (v NullableContainerContainerPushRepositoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerContainerPushRepositoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


