/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"fmt"
)

// checks if the FileFileRemote type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileFileRemote{}

// FileFileRemote Serializer for File Remotes.
type FileFileRemote struct {
	// A unique name for this remote.
	Name string `json:"name"`
	// The URL of an external content source.
	Url string `json:"url"`
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
	// The policy to use when downloading content. The possible values include: 'immediate', 'on_demand', and 'streamed'. 'immediate' is the default.* `immediate` - When syncing, download all metadata and content now.* `on_demand` - When syncing, download metadata, but do not download content now. Instead, download content as clients request it, and save it in Pulp to be served for future client requests.* `streamed` - When syncing, download metadata, but do not download content now. Instead,download content as clients request it, but never save it in Pulp. This causes future requests for that same content to have to be downloaded again.
	Policy *Policy692Enum `json:"policy,omitempty"`
	// A PEM encoded CA certificate used to validate the server certificate presented by the remote server.
	CaCert *string `json:"ca_cert,omitempty"`
	// A PEM encoded client certificate used for authentication.
	ClientCert *string `json:"client_cert,omitempty"`
	// A PEM encoded private key used for authentication.
	ClientKey *string `json:"client_key,omitempty"`
	// If True, TLS peer validation must be performed.
	TlsValidation *bool `json:"tls_validation,omitempty"`
	// The proxy URL. Format: scheme://host:port
	ProxyUrl *string `json:"proxy_url,omitempty"`
	// The username to authenticte to the proxy.
	ProxyUsername *string `json:"proxy_username,omitempty"`
	// The password to authenticate to the proxy. Extra leading and trailing whitespace characters are not trimmed.
	ProxyPassword *string `json:"proxy_password,omitempty"`
	// The username to be used for authentication when syncing.
	Username *string `json:"username,omitempty"`
	// The password to be used for authentication when syncing. Extra leading and trailing whitespace characters are not trimmed.
	Password *string `json:"password,omitempty"`
	// Maximum number of retry attempts after a download failure. If not set then the default value (3) will be used.
	MaxRetries *int64 `json:"max_retries,omitempty"`
	// aiohttp.ClientTimeout.total (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	TotalTimeout *float64 `json:"total_timeout,omitempty"`
	// aiohttp.ClientTimeout.connect (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	ConnectTimeout *float64 `json:"connect_timeout,omitempty"`
	// aiohttp.ClientTimeout.sock_connect (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	SockConnectTimeout *float64 `json:"sock_connect_timeout,omitempty"`
	// aiohttp.ClientTimeout.sock_read (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	SockReadTimeout *float64 `json:"sock_read_timeout,omitempty"`
	// Headers for aiohttp.Clientsession
	Headers []map[string]interface{} `json:"headers,omitempty"`
	// Total number of simultaneous connections. If not set then the default value will be used.
	DownloadConcurrency *int64 `json:"download_concurrency,omitempty"`
	// Limits requests per second for each concurrent downloader
	RateLimit *int64 `json:"rate_limit,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FileFileRemote FileFileRemote

// NewFileFileRemote instantiates a new FileFileRemote object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileFileRemote(name string, url string) *FileFileRemote {
	this := FileFileRemote{}
	this.Name = name
	this.Url = url
	var policy Policy692Enum = POLICY692ENUM_IMMEDIATE
	this.Policy = &policy
	return &this
}

// NewFileFileRemoteWithDefaults instantiates a new FileFileRemote object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileFileRemoteWithDefaults() *FileFileRemote {
	this := FileFileRemote{}
	var policy Policy692Enum = POLICY692ENUM_IMMEDIATE
	this.Policy = &policy
	return &this
}

// GetName returns the Name field value
func (o *FileFileRemote) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FileFileRemote) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *FileFileRemote) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *FileFileRemote) SetUrl(v string) {
	o.Url = v
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *FileFileRemote) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *FileFileRemote) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *FileFileRemote) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *FileFileRemote) GetPolicy() Policy692Enum {
	if o == nil || IsNil(o.Policy) {
		var ret Policy692Enum
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetPolicyOk() (*Policy692Enum, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *FileFileRemote) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given Policy692Enum and assigns it to the Policy field.
func (o *FileFileRemote) SetPolicy(v Policy692Enum) {
	o.Policy = &v
}

// GetCaCert returns the CaCert field value if set, zero value otherwise.
func (o *FileFileRemote) GetCaCert() string {
	if o == nil || IsNil(o.CaCert) {
		var ret string
		return ret
	}
	return *o.CaCert
}

// GetCaCertOk returns a tuple with the CaCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetCaCertOk() (*string, bool) {
	if o == nil || IsNil(o.CaCert) {
		return nil, false
	}
	return o.CaCert, true
}

// HasCaCert returns a boolean if a field has been set.
func (o *FileFileRemote) HasCaCert() bool {
	if o != nil && !IsNil(o.CaCert) {
		return true
	}

	return false
}

// SetCaCert gets a reference to the given string and assigns it to the CaCert field.
func (o *FileFileRemote) SetCaCert(v string) {
	o.CaCert = &v
}

// GetClientCert returns the ClientCert field value if set, zero value otherwise.
func (o *FileFileRemote) GetClientCert() string {
	if o == nil || IsNil(o.ClientCert) {
		var ret string
		return ret
	}
	return *o.ClientCert
}

// GetClientCertOk returns a tuple with the ClientCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetClientCertOk() (*string, bool) {
	if o == nil || IsNil(o.ClientCert) {
		return nil, false
	}
	return o.ClientCert, true
}

// HasClientCert returns a boolean if a field has been set.
func (o *FileFileRemote) HasClientCert() bool {
	if o != nil && !IsNil(o.ClientCert) {
		return true
	}

	return false
}

// SetClientCert gets a reference to the given string and assigns it to the ClientCert field.
func (o *FileFileRemote) SetClientCert(v string) {
	o.ClientCert = &v
}

// GetClientKey returns the ClientKey field value if set, zero value otherwise.
func (o *FileFileRemote) GetClientKey() string {
	if o == nil || IsNil(o.ClientKey) {
		var ret string
		return ret
	}
	return *o.ClientKey
}

// GetClientKeyOk returns a tuple with the ClientKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetClientKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ClientKey) {
		return nil, false
	}
	return o.ClientKey, true
}

// HasClientKey returns a boolean if a field has been set.
func (o *FileFileRemote) HasClientKey() bool {
	if o != nil && !IsNil(o.ClientKey) {
		return true
	}

	return false
}

// SetClientKey gets a reference to the given string and assigns it to the ClientKey field.
func (o *FileFileRemote) SetClientKey(v string) {
	o.ClientKey = &v
}

// GetTlsValidation returns the TlsValidation field value if set, zero value otherwise.
func (o *FileFileRemote) GetTlsValidation() bool {
	if o == nil || IsNil(o.TlsValidation) {
		var ret bool
		return ret
	}
	return *o.TlsValidation
}

// GetTlsValidationOk returns a tuple with the TlsValidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetTlsValidationOk() (*bool, bool) {
	if o == nil || IsNil(o.TlsValidation) {
		return nil, false
	}
	return o.TlsValidation, true
}

// HasTlsValidation returns a boolean if a field has been set.
func (o *FileFileRemote) HasTlsValidation() bool {
	if o != nil && !IsNil(o.TlsValidation) {
		return true
	}

	return false
}

// SetTlsValidation gets a reference to the given bool and assigns it to the TlsValidation field.
func (o *FileFileRemote) SetTlsValidation(v bool) {
	o.TlsValidation = &v
}

// GetProxyUrl returns the ProxyUrl field value if set, zero value otherwise.
func (o *FileFileRemote) GetProxyUrl() string {
	if o == nil || IsNil(o.ProxyUrl) {
		var ret string
		return ret
	}
	return *o.ProxyUrl
}

// GetProxyUrlOk returns a tuple with the ProxyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetProxyUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyUrl) {
		return nil, false
	}
	return o.ProxyUrl, true
}

// HasProxyUrl returns a boolean if a field has been set.
func (o *FileFileRemote) HasProxyUrl() bool {
	if o != nil && !IsNil(o.ProxyUrl) {
		return true
	}

	return false
}

// SetProxyUrl gets a reference to the given string and assigns it to the ProxyUrl field.
func (o *FileFileRemote) SetProxyUrl(v string) {
	o.ProxyUrl = &v
}

// GetProxyUsername returns the ProxyUsername field value if set, zero value otherwise.
func (o *FileFileRemote) GetProxyUsername() string {
	if o == nil || IsNil(o.ProxyUsername) {
		var ret string
		return ret
	}
	return *o.ProxyUsername
}

// GetProxyUsernameOk returns a tuple with the ProxyUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetProxyUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyUsername) {
		return nil, false
	}
	return o.ProxyUsername, true
}

// HasProxyUsername returns a boolean if a field has been set.
func (o *FileFileRemote) HasProxyUsername() bool {
	if o != nil && !IsNil(o.ProxyUsername) {
		return true
	}

	return false
}

// SetProxyUsername gets a reference to the given string and assigns it to the ProxyUsername field.
func (o *FileFileRemote) SetProxyUsername(v string) {
	o.ProxyUsername = &v
}

// GetProxyPassword returns the ProxyPassword field value if set, zero value otherwise.
func (o *FileFileRemote) GetProxyPassword() string {
	if o == nil || IsNil(o.ProxyPassword) {
		var ret string
		return ret
	}
	return *o.ProxyPassword
}

// GetProxyPasswordOk returns a tuple with the ProxyPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetProxyPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyPassword) {
		return nil, false
	}
	return o.ProxyPassword, true
}

// HasProxyPassword returns a boolean if a field has been set.
func (o *FileFileRemote) HasProxyPassword() bool {
	if o != nil && !IsNil(o.ProxyPassword) {
		return true
	}

	return false
}

// SetProxyPassword gets a reference to the given string and assigns it to the ProxyPassword field.
func (o *FileFileRemote) SetProxyPassword(v string) {
	o.ProxyPassword = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *FileFileRemote) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *FileFileRemote) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *FileFileRemote) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *FileFileRemote) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *FileFileRemote) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *FileFileRemote) SetPassword(v string) {
	o.Password = &v
}

// GetMaxRetries returns the MaxRetries field value if set, zero value otherwise.
func (o *FileFileRemote) GetMaxRetries() int64 {
	if o == nil || IsNil(o.MaxRetries) {
		var ret int64
		return ret
	}
	return *o.MaxRetries
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetMaxRetriesOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxRetries) {
		return nil, false
	}
	return o.MaxRetries, true
}

// HasMaxRetries returns a boolean if a field has been set.
func (o *FileFileRemote) HasMaxRetries() bool {
	if o != nil && !IsNil(o.MaxRetries) {
		return true
	}

	return false
}

// SetMaxRetries gets a reference to the given int64 and assigns it to the MaxRetries field.
func (o *FileFileRemote) SetMaxRetries(v int64) {
	o.MaxRetries = &v
}

// GetTotalTimeout returns the TotalTimeout field value if set, zero value otherwise.
func (o *FileFileRemote) GetTotalTimeout() float64 {
	if o == nil || IsNil(o.TotalTimeout) {
		var ret float64
		return ret
	}
	return *o.TotalTimeout
}

// GetTotalTimeoutOk returns a tuple with the TotalTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetTotalTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalTimeout) {
		return nil, false
	}
	return o.TotalTimeout, true
}

// HasTotalTimeout returns a boolean if a field has been set.
func (o *FileFileRemote) HasTotalTimeout() bool {
	if o != nil && !IsNil(o.TotalTimeout) {
		return true
	}

	return false
}

// SetTotalTimeout gets a reference to the given float64 and assigns it to the TotalTimeout field.
func (o *FileFileRemote) SetTotalTimeout(v float64) {
	o.TotalTimeout = &v
}

// GetConnectTimeout returns the ConnectTimeout field value if set, zero value otherwise.
func (o *FileFileRemote) GetConnectTimeout() float64 {
	if o == nil || IsNil(o.ConnectTimeout) {
		var ret float64
		return ret
	}
	return *o.ConnectTimeout
}

// GetConnectTimeoutOk returns a tuple with the ConnectTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetConnectTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.ConnectTimeout) {
		return nil, false
	}
	return o.ConnectTimeout, true
}

// HasConnectTimeout returns a boolean if a field has been set.
func (o *FileFileRemote) HasConnectTimeout() bool {
	if o != nil && !IsNil(o.ConnectTimeout) {
		return true
	}

	return false
}

// SetConnectTimeout gets a reference to the given float64 and assigns it to the ConnectTimeout field.
func (o *FileFileRemote) SetConnectTimeout(v float64) {
	o.ConnectTimeout = &v
}

// GetSockConnectTimeout returns the SockConnectTimeout field value if set, zero value otherwise.
func (o *FileFileRemote) GetSockConnectTimeout() float64 {
	if o == nil || IsNil(o.SockConnectTimeout) {
		var ret float64
		return ret
	}
	return *o.SockConnectTimeout
}

// GetSockConnectTimeoutOk returns a tuple with the SockConnectTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetSockConnectTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.SockConnectTimeout) {
		return nil, false
	}
	return o.SockConnectTimeout, true
}

// HasSockConnectTimeout returns a boolean if a field has been set.
func (o *FileFileRemote) HasSockConnectTimeout() bool {
	if o != nil && !IsNil(o.SockConnectTimeout) {
		return true
	}

	return false
}

// SetSockConnectTimeout gets a reference to the given float64 and assigns it to the SockConnectTimeout field.
func (o *FileFileRemote) SetSockConnectTimeout(v float64) {
	o.SockConnectTimeout = &v
}

// GetSockReadTimeout returns the SockReadTimeout field value if set, zero value otherwise.
func (o *FileFileRemote) GetSockReadTimeout() float64 {
	if o == nil || IsNil(o.SockReadTimeout) {
		var ret float64
		return ret
	}
	return *o.SockReadTimeout
}

// GetSockReadTimeoutOk returns a tuple with the SockReadTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetSockReadTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.SockReadTimeout) {
		return nil, false
	}
	return o.SockReadTimeout, true
}

// HasSockReadTimeout returns a boolean if a field has been set.
func (o *FileFileRemote) HasSockReadTimeout() bool {
	if o != nil && !IsNil(o.SockReadTimeout) {
		return true
	}

	return false
}

// SetSockReadTimeout gets a reference to the given float64 and assigns it to the SockReadTimeout field.
func (o *FileFileRemote) SetSockReadTimeout(v float64) {
	o.SockReadTimeout = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *FileFileRemote) GetHeaders() []map[string]interface{} {
	if o == nil || IsNil(o.Headers) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetHeadersOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *FileFileRemote) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []map[string]interface{} and assigns it to the Headers field.
func (o *FileFileRemote) SetHeaders(v []map[string]interface{}) {
	o.Headers = v
}

// GetDownloadConcurrency returns the DownloadConcurrency field value if set, zero value otherwise.
func (o *FileFileRemote) GetDownloadConcurrency() int64 {
	if o == nil || IsNil(o.DownloadConcurrency) {
		var ret int64
		return ret
	}
	return *o.DownloadConcurrency
}

// GetDownloadConcurrencyOk returns a tuple with the DownloadConcurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetDownloadConcurrencyOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadConcurrency) {
		return nil, false
	}
	return o.DownloadConcurrency, true
}

// HasDownloadConcurrency returns a boolean if a field has been set.
func (o *FileFileRemote) HasDownloadConcurrency() bool {
	if o != nil && !IsNil(o.DownloadConcurrency) {
		return true
	}

	return false
}

// SetDownloadConcurrency gets a reference to the given int64 and assigns it to the DownloadConcurrency field.
func (o *FileFileRemote) SetDownloadConcurrency(v int64) {
	o.DownloadConcurrency = &v
}

// GetRateLimit returns the RateLimit field value if set, zero value otherwise.
func (o *FileFileRemote) GetRateLimit() int64 {
	if o == nil || IsNil(o.RateLimit) {
		var ret int64
		return ret
	}
	return *o.RateLimit
}

// GetRateLimitOk returns a tuple with the RateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileFileRemote) GetRateLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.RateLimit) {
		return nil, false
	}
	return o.RateLimit, true
}

// HasRateLimit returns a boolean if a field has been set.
func (o *FileFileRemote) HasRateLimit() bool {
	if o != nil && !IsNil(o.RateLimit) {
		return true
	}

	return false
}

// SetRateLimit gets a reference to the given int64 and assigns it to the RateLimit field.
func (o *FileFileRemote) SetRateLimit(v int64) {
	o.RateLimit = &v
}

func (o FileFileRemote) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileFileRemote) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.CaCert) {
		toSerialize["ca_cert"] = o.CaCert
	}
	if !IsNil(o.ClientCert) {
		toSerialize["client_cert"] = o.ClientCert
	}
	if !IsNil(o.ClientKey) {
		toSerialize["client_key"] = o.ClientKey
	}
	if !IsNil(o.TlsValidation) {
		toSerialize["tls_validation"] = o.TlsValidation
	}
	if !IsNil(o.ProxyUrl) {
		toSerialize["proxy_url"] = o.ProxyUrl
	}
	if !IsNil(o.ProxyUsername) {
		toSerialize["proxy_username"] = o.ProxyUsername
	}
	if !IsNil(o.ProxyPassword) {
		toSerialize["proxy_password"] = o.ProxyPassword
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.MaxRetries) {
		toSerialize["max_retries"] = o.MaxRetries
	}
	if !IsNil(o.TotalTimeout) {
		toSerialize["total_timeout"] = o.TotalTimeout
	}
	if !IsNil(o.ConnectTimeout) {
		toSerialize["connect_timeout"] = o.ConnectTimeout
	}
	if !IsNil(o.SockConnectTimeout) {
		toSerialize["sock_connect_timeout"] = o.SockConnectTimeout
	}
	if !IsNil(o.SockReadTimeout) {
		toSerialize["sock_read_timeout"] = o.SockReadTimeout
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.DownloadConcurrency) {
		toSerialize["download_concurrency"] = o.DownloadConcurrency
	}
	if !IsNil(o.RateLimit) {
		toSerialize["rate_limit"] = o.RateLimit
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FileFileRemote) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileFileRemote := _FileFileRemote{}

	err = json.Unmarshal(data, &varFileFileRemote)

	if err != nil {
		return err
	}

	*o = FileFileRemote(varFileFileRemote)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "url")
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "policy")
		delete(additionalProperties, "ca_cert")
		delete(additionalProperties, "client_cert")
		delete(additionalProperties, "client_key")
		delete(additionalProperties, "tls_validation")
		delete(additionalProperties, "proxy_url")
		delete(additionalProperties, "proxy_username")
		delete(additionalProperties, "proxy_password")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		delete(additionalProperties, "max_retries")
		delete(additionalProperties, "total_timeout")
		delete(additionalProperties, "connect_timeout")
		delete(additionalProperties, "sock_connect_timeout")
		delete(additionalProperties, "sock_read_timeout")
		delete(additionalProperties, "headers")
		delete(additionalProperties, "download_concurrency")
		delete(additionalProperties, "rate_limit")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFileFileRemote struct {
	value *FileFileRemote
	isSet bool
}

func (v NullableFileFileRemote) Get() *FileFileRemote {
	return v.value
}

func (v *NullableFileFileRemote) Set(val *FileFileRemote) {
	v.value = val
	v.isSet = true
}

func (v NullableFileFileRemote) IsSet() bool {
	return v.isSet
}

func (v *NullableFileFileRemote) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileFileRemote(val *FileFileRemote) *NullableFileFileRemote {
	return &NullableFileFileRemote{value: val, isSet: true}
}

func (v NullableFileFileRemote) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileFileRemote) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


