/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedrpmRpmRepositoryResponseList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedrpmRpmRepositoryResponseList{}

// PaginatedrpmRpmRepositoryResponseList struct for PaginatedrpmRpmRepositoryResponseList
type PaginatedrpmRpmRepositoryResponseList struct {
	Count int32 `json:"count"`
	Next *string `json:"next,omitempty"`
	Previous *string `json:"previous,omitempty"`
	Results []RpmRpmRepositoryResponse `json:"results"`
}

type _PaginatedrpmRpmRepositoryResponseList PaginatedrpmRpmRepositoryResponseList

// NewPaginatedrpmRpmRepositoryResponseList instantiates a new PaginatedrpmRpmRepositoryResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedrpmRpmRepositoryResponseList(count int32, results []RpmRpmRepositoryResponse) *PaginatedrpmRpmRepositoryResponseList {
	this := PaginatedrpmRpmRepositoryResponseList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedrpmRpmRepositoryResponseListWithDefaults instantiates a new PaginatedrpmRpmRepositoryResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedrpmRpmRepositoryResponseListWithDefaults() *PaginatedrpmRpmRepositoryResponseList {
	this := PaginatedrpmRpmRepositoryResponseList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedrpmRpmRepositoryResponseList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedrpmRpmRepositoryResponseList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedrpmRpmRepositoryResponseList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedrpmRpmRepositoryResponseList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedrpmRpmRepositoryResponseList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedrpmRpmRepositoryResponseList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedrpmRpmRepositoryResponseList) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedrpmRpmRepositoryResponseList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedrpmRpmRepositoryResponseList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedrpmRpmRepositoryResponseList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedrpmRpmRepositoryResponseList) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value
func (o *PaginatedrpmRpmRepositoryResponseList) GetResults() []RpmRpmRepositoryResponse {
	if o == nil {
		var ret []RpmRpmRepositoryResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedrpmRpmRepositoryResponseList) GetResultsOk() ([]RpmRpmRepositoryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedrpmRpmRepositoryResponseList) SetResults(v []RpmRpmRepositoryResponse) {
	o.Results = v
}

func (o PaginatedrpmRpmRepositoryResponseList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedrpmRpmRepositoryResponseList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedrpmRpmRepositoryResponseList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedrpmRpmRepositoryResponseList := _PaginatedrpmRpmRepositoryResponseList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedrpmRpmRepositoryResponseList)

	if err != nil {
		return err
	}

	*o = PaginatedrpmRpmRepositoryResponseList(varPaginatedrpmRpmRepositoryResponseList)

	return err
}

type NullablePaginatedrpmRpmRepositoryResponseList struct {
	value *PaginatedrpmRpmRepositoryResponseList
	isSet bool
}

func (v NullablePaginatedrpmRpmRepositoryResponseList) Get() *PaginatedrpmRpmRepositoryResponseList {
	return v.value
}

func (v *NullablePaginatedrpmRpmRepositoryResponseList) Set(val *PaginatedrpmRpmRepositoryResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedrpmRpmRepositoryResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedrpmRpmRepositoryResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedrpmRpmRepositoryResponseList(val *PaginatedrpmRpmRepositoryResponseList) *NullablePaginatedrpmRpmRepositoryResponseList {
	return &NullablePaginatedrpmRpmRepositoryResponseList{value: val, isSet: true}
}

func (v NullablePaginatedrpmRpmRepositoryResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedrpmRpmRepositoryResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


