/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedHeaderContentGuardResponseList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedHeaderContentGuardResponseList{}

// PaginatedHeaderContentGuardResponseList struct for PaginatedHeaderContentGuardResponseList
type PaginatedHeaderContentGuardResponseList struct {
	Count int32 `json:"count"`
	Next *string `json:"next,omitempty"`
	Previous *string `json:"previous,omitempty"`
	Results []HeaderContentGuardResponse `json:"results"`
}

type _PaginatedHeaderContentGuardResponseList PaginatedHeaderContentGuardResponseList

// NewPaginatedHeaderContentGuardResponseList instantiates a new PaginatedHeaderContentGuardResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedHeaderContentGuardResponseList(count int32, results []HeaderContentGuardResponse) *PaginatedHeaderContentGuardResponseList {
	this := PaginatedHeaderContentGuardResponseList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedHeaderContentGuardResponseListWithDefaults instantiates a new PaginatedHeaderContentGuardResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedHeaderContentGuardResponseListWithDefaults() *PaginatedHeaderContentGuardResponseList {
	this := PaginatedHeaderContentGuardResponseList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedHeaderContentGuardResponseList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedHeaderContentGuardResponseList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedHeaderContentGuardResponseList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedHeaderContentGuardResponseList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedHeaderContentGuardResponseList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedHeaderContentGuardResponseList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedHeaderContentGuardResponseList) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedHeaderContentGuardResponseList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedHeaderContentGuardResponseList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedHeaderContentGuardResponseList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedHeaderContentGuardResponseList) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value
func (o *PaginatedHeaderContentGuardResponseList) GetResults() []HeaderContentGuardResponse {
	if o == nil {
		var ret []HeaderContentGuardResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedHeaderContentGuardResponseList) GetResultsOk() ([]HeaderContentGuardResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedHeaderContentGuardResponseList) SetResults(v []HeaderContentGuardResponse) {
	o.Results = v
}

func (o PaginatedHeaderContentGuardResponseList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedHeaderContentGuardResponseList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedHeaderContentGuardResponseList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedHeaderContentGuardResponseList := _PaginatedHeaderContentGuardResponseList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedHeaderContentGuardResponseList)

	if err != nil {
		return err
	}

	*o = PaginatedHeaderContentGuardResponseList(varPaginatedHeaderContentGuardResponseList)

	return err
}

type NullablePaginatedHeaderContentGuardResponseList struct {
	value *PaginatedHeaderContentGuardResponseList
	isSet bool
}

func (v NullablePaginatedHeaderContentGuardResponseList) Get() *PaginatedHeaderContentGuardResponseList {
	return v.value
}

func (v *NullablePaginatedHeaderContentGuardResponseList) Set(val *PaginatedHeaderContentGuardResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedHeaderContentGuardResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedHeaderContentGuardResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedHeaderContentGuardResponseList(val *PaginatedHeaderContentGuardResponseList) *NullablePaginatedHeaderContentGuardResponseList {
	return &NullablePaginatedHeaderContentGuardResponseList{value: val, isSet: true}
}

func (v NullablePaginatedHeaderContentGuardResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedHeaderContentGuardResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


