/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedgemGemContentResponseList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedgemGemContentResponseList{}

// PaginatedgemGemContentResponseList struct for PaginatedgemGemContentResponseList
type PaginatedgemGemContentResponseList struct {
	Count int32 `json:"count"`
	Next *string `json:"next,omitempty"`
	Previous *string `json:"previous,omitempty"`
	Results []GemGemContentResponse `json:"results"`
}

type _PaginatedgemGemContentResponseList PaginatedgemGemContentResponseList

// NewPaginatedgemGemContentResponseList instantiates a new PaginatedgemGemContentResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedgemGemContentResponseList(count int32, results []GemGemContentResponse) *PaginatedgemGemContentResponseList {
	this := PaginatedgemGemContentResponseList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedgemGemContentResponseListWithDefaults instantiates a new PaginatedgemGemContentResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedgemGemContentResponseListWithDefaults() *PaginatedgemGemContentResponseList {
	this := PaginatedgemGemContentResponseList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedgemGemContentResponseList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedgemGemContentResponseList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedgemGemContentResponseList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedgemGemContentResponseList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedgemGemContentResponseList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedgemGemContentResponseList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedgemGemContentResponseList) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedgemGemContentResponseList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedgemGemContentResponseList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedgemGemContentResponseList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedgemGemContentResponseList) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value
func (o *PaginatedgemGemContentResponseList) GetResults() []GemGemContentResponse {
	if o == nil {
		var ret []GemGemContentResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedgemGemContentResponseList) GetResultsOk() ([]GemGemContentResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedgemGemContentResponseList) SetResults(v []GemGemContentResponse) {
	o.Results = v
}

func (o PaginatedgemGemContentResponseList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedgemGemContentResponseList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedgemGemContentResponseList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedgemGemContentResponseList := _PaginatedgemGemContentResponseList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedgemGemContentResponseList)

	if err != nil {
		return err
	}

	*o = PaginatedgemGemContentResponseList(varPaginatedgemGemContentResponseList)

	return err
}

type NullablePaginatedgemGemContentResponseList struct {
	value *PaginatedgemGemContentResponseList
	isSet bool
}

func (v NullablePaginatedgemGemContentResponseList) Get() *PaginatedgemGemContentResponseList {
	return v.value
}

func (v *NullablePaginatedgemGemContentResponseList) Set(val *PaginatedgemGemContentResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedgemGemContentResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedgemGemContentResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedgemGemContentResponseList(val *PaginatedgemGemContentResponseList) *NullablePaginatedgemGemContentResponseList {
	return &NullablePaginatedgemGemContentResponseList{value: val, isSet: true}
}

func (v NullablePaginatedgemGemContentResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedgemGemContentResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


