/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedOpenPGPPublicKeyResponseList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedOpenPGPPublicKeyResponseList{}

// PaginatedOpenPGPPublicKeyResponseList struct for PaginatedOpenPGPPublicKeyResponseList
type PaginatedOpenPGPPublicKeyResponseList struct {
	Count int32 `json:"count"`
	Next *string `json:"next,omitempty"`
	Previous *string `json:"previous,omitempty"`
	Results []OpenPGPPublicKeyResponse `json:"results"`
}

type _PaginatedOpenPGPPublicKeyResponseList PaginatedOpenPGPPublicKeyResponseList

// NewPaginatedOpenPGPPublicKeyResponseList instantiates a new PaginatedOpenPGPPublicKeyResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedOpenPGPPublicKeyResponseList(count int32, results []OpenPGPPublicKeyResponse) *PaginatedOpenPGPPublicKeyResponseList {
	this := PaginatedOpenPGPPublicKeyResponseList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedOpenPGPPublicKeyResponseListWithDefaults instantiates a new PaginatedOpenPGPPublicKeyResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedOpenPGPPublicKeyResponseListWithDefaults() *PaginatedOpenPGPPublicKeyResponseList {
	this := PaginatedOpenPGPPublicKeyResponseList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedOpenPGPPublicKeyResponseList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedOpenPGPPublicKeyResponseList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedOpenPGPPublicKeyResponseList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedOpenPGPPublicKeyResponseList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedOpenPGPPublicKeyResponseList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedOpenPGPPublicKeyResponseList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedOpenPGPPublicKeyResponseList) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedOpenPGPPublicKeyResponseList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedOpenPGPPublicKeyResponseList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedOpenPGPPublicKeyResponseList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedOpenPGPPublicKeyResponseList) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value
func (o *PaginatedOpenPGPPublicKeyResponseList) GetResults() []OpenPGPPublicKeyResponse {
	if o == nil {
		var ret []OpenPGPPublicKeyResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedOpenPGPPublicKeyResponseList) GetResultsOk() ([]OpenPGPPublicKeyResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedOpenPGPPublicKeyResponseList) SetResults(v []OpenPGPPublicKeyResponse) {
	o.Results = v
}

func (o PaginatedOpenPGPPublicKeyResponseList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedOpenPGPPublicKeyResponseList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedOpenPGPPublicKeyResponseList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedOpenPGPPublicKeyResponseList := _PaginatedOpenPGPPublicKeyResponseList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedOpenPGPPublicKeyResponseList)

	if err != nil {
		return err
	}

	*o = PaginatedOpenPGPPublicKeyResponseList(varPaginatedOpenPGPPublicKeyResponseList)

	return err
}

type NullablePaginatedOpenPGPPublicKeyResponseList struct {
	value *PaginatedOpenPGPPublicKeyResponseList
	isSet bool
}

func (v NullablePaginatedOpenPGPPublicKeyResponseList) Get() *PaginatedOpenPGPPublicKeyResponseList {
	return v.value
}

func (v *NullablePaginatedOpenPGPPublicKeyResponseList) Set(val *PaginatedOpenPGPPublicKeyResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedOpenPGPPublicKeyResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedOpenPGPPublicKeyResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedOpenPGPPublicKeyResponseList(val *PaginatedOpenPGPPublicKeyResponseList) *NullablePaginatedOpenPGPPublicKeyResponseList {
	return &NullablePaginatedOpenPGPPublicKeyResponseList{value: val, isSet: true}
}

func (v NullablePaginatedOpenPGPPublicKeyResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedOpenPGPPublicKeyResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


