/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GroupRoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupRoleResponse{}

// GroupRoleResponse Serializer for GroupRole.
type GroupRoleResponse struct {
	PulpHref *string `json:"pulp_href,omitempty"`
	// The Pulp Resource Name (PRN).
	Prn *string `json:"prn,omitempty"`
	// Timestamp of creation.
	PulpCreated *time.Time `json:"pulp_created,omitempty"`
	// Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.
	PulpLastUpdated *time.Time `json:"pulp_last_updated,omitempty"`
	Role string `json:"role"`
	// pulp_href of the object for which role permissions should be asserted. If set to 'null', permissions will act on the model-level.
	ContentObject *string `json:"content_object,omitempty"`
	// prn of the object for which role permissions should be asserted. If set to 'null', permissions will act on either domain or model-level.
	ContentObjectPrn *string `json:"content_object_prn,omitempty"`
	Description *string `json:"description,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
	// Domain this role should be applied on, mutually exclusive with content_object.
	Domain *string `json:"domain,omitempty"`
}

type _GroupRoleResponse GroupRoleResponse

// NewGroupRoleResponse instantiates a new GroupRoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupRoleResponse(role string) *GroupRoleResponse {
	this := GroupRoleResponse{}
	this.Role = role
	return &this
}

// NewGroupRoleResponseWithDefaults instantiates a new GroupRoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupRoleResponseWithDefaults() *GroupRoleResponse {
	this := GroupRoleResponse{}
	return &this
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetPulpHref() string {
	if o == nil || IsNil(o.PulpHref) {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || IsNil(o.PulpHref) {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasPulpHref() bool {
	if o != nil && !IsNil(o.PulpHref) {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *GroupRoleResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetPrn returns the Prn field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetPrn() string {
	if o == nil || IsNil(o.Prn) {
		var ret string
		return ret
	}
	return *o.Prn
}

// GetPrnOk returns a tuple with the Prn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetPrnOk() (*string, bool) {
	if o == nil || IsNil(o.Prn) {
		return nil, false
	}
	return o.Prn, true
}

// HasPrn returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasPrn() bool {
	if o != nil && !IsNil(o.Prn) {
		return true
	}

	return false
}

// SetPrn gets a reference to the given string and assigns it to the Prn field.
func (o *GroupRoleResponse) SetPrn(v string) {
	o.Prn = &v
}

// GetPulpCreated returns the PulpCreated field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetPulpCreated() time.Time {
	if o == nil || IsNil(o.PulpCreated) {
		var ret time.Time
		return ret
	}
	return *o.PulpCreated
}

// GetPulpCreatedOk returns a tuple with the PulpCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetPulpCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpCreated) {
		return nil, false
	}
	return o.PulpCreated, true
}

// HasPulpCreated returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasPulpCreated() bool {
	if o != nil && !IsNil(o.PulpCreated) {
		return true
	}

	return false
}

// SetPulpCreated gets a reference to the given time.Time and assigns it to the PulpCreated field.
func (o *GroupRoleResponse) SetPulpCreated(v time.Time) {
	o.PulpCreated = &v
}

// GetPulpLastUpdated returns the PulpLastUpdated field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetPulpLastUpdated() time.Time {
	if o == nil || IsNil(o.PulpLastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.PulpLastUpdated
}

// GetPulpLastUpdatedOk returns a tuple with the PulpLastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetPulpLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpLastUpdated) {
		return nil, false
	}
	return o.PulpLastUpdated, true
}

// HasPulpLastUpdated returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasPulpLastUpdated() bool {
	if o != nil && !IsNil(o.PulpLastUpdated) {
		return true
	}

	return false
}

// SetPulpLastUpdated gets a reference to the given time.Time and assigns it to the PulpLastUpdated field.
func (o *GroupRoleResponse) SetPulpLastUpdated(v time.Time) {
	o.PulpLastUpdated = &v
}

// GetRole returns the Role field value
func (o *GroupRoleResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GroupRoleResponse) SetRole(v string) {
	o.Role = v
}

// GetContentObject returns the ContentObject field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetContentObject() string {
	if o == nil || IsNil(o.ContentObject) {
		var ret string
		return ret
	}
	return *o.ContentObject
}

// GetContentObjectOk returns a tuple with the ContentObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetContentObjectOk() (*string, bool) {
	if o == nil || IsNil(o.ContentObject) {
		return nil, false
	}
	return o.ContentObject, true
}

// HasContentObject returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasContentObject() bool {
	if o != nil && !IsNil(o.ContentObject) {
		return true
	}

	return false
}

// SetContentObject gets a reference to the given string and assigns it to the ContentObject field.
func (o *GroupRoleResponse) SetContentObject(v string) {
	o.ContentObject = &v
}

// GetContentObjectPrn returns the ContentObjectPrn field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetContentObjectPrn() string {
	if o == nil || IsNil(o.ContentObjectPrn) {
		var ret string
		return ret
	}
	return *o.ContentObjectPrn
}

// GetContentObjectPrnOk returns a tuple with the ContentObjectPrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetContentObjectPrnOk() (*string, bool) {
	if o == nil || IsNil(o.ContentObjectPrn) {
		return nil, false
	}
	return o.ContentObjectPrn, true
}

// HasContentObjectPrn returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasContentObjectPrn() bool {
	if o != nil && !IsNil(o.ContentObjectPrn) {
		return true
	}

	return false
}

// SetContentObjectPrn gets a reference to the given string and assigns it to the ContentObjectPrn field.
func (o *GroupRoleResponse) SetContentObjectPrn(v string) {
	o.ContentObjectPrn = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GroupRoleResponse) SetDescription(v string) {
	o.Description = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetPermissions() []string {
	if o == nil || IsNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *GroupRoleResponse) SetPermissions(v []string) {
	o.Permissions = v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *GroupRoleResponse) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRoleResponse) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *GroupRoleResponse) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *GroupRoleResponse) SetDomain(v string) {
	o.Domain = &v
}

func (o GroupRoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupRoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpHref) {
		toSerialize["pulp_href"] = o.PulpHref
	}
	if !IsNil(o.Prn) {
		toSerialize["prn"] = o.Prn
	}
	if !IsNil(o.PulpCreated) {
		toSerialize["pulp_created"] = o.PulpCreated
	}
	if !IsNil(o.PulpLastUpdated) {
		toSerialize["pulp_last_updated"] = o.PulpLastUpdated
	}
	toSerialize["role"] = o.Role
	if !IsNil(o.ContentObject) {
		toSerialize["content_object"] = o.ContentObject
	}
	if !IsNil(o.ContentObjectPrn) {
		toSerialize["content_object_prn"] = o.ContentObjectPrn
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	return toSerialize, nil
}

func (o *GroupRoleResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupRoleResponse := _GroupRoleResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupRoleResponse)

	if err != nil {
		return err
	}

	*o = GroupRoleResponse(varGroupRoleResponse)

	return err
}

type NullableGroupRoleResponse struct {
	value *GroupRoleResponse
	isSet bool
}

func (v NullableGroupRoleResponse) Get() *GroupRoleResponse {
	return v.value
}

func (v *NullableGroupRoleResponse) Set(val *GroupRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupRoleResponse(val *GroupRoleResponse) *NullableGroupRoleResponse {
	return &NullableGroupRoleResponse{value: val, isSet: true}
}

func (v NullableGroupRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


