/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedpythonPythonPublicationResponseList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedpythonPythonPublicationResponseList{}

// PaginatedpythonPythonPublicationResponseList struct for PaginatedpythonPythonPublicationResponseList
type PaginatedpythonPythonPublicationResponseList struct {
	Count int32 `json:"count"`
	Next *string `json:"next,omitempty"`
	Previous *string `json:"previous,omitempty"`
	Results []PythonPythonPublicationResponse `json:"results"`
}

type _PaginatedpythonPythonPublicationResponseList PaginatedpythonPythonPublicationResponseList

// NewPaginatedpythonPythonPublicationResponseList instantiates a new PaginatedpythonPythonPublicationResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedpythonPythonPublicationResponseList(count int32, results []PythonPythonPublicationResponse) *PaginatedpythonPythonPublicationResponseList {
	this := PaginatedpythonPythonPublicationResponseList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedpythonPythonPublicationResponseListWithDefaults instantiates a new PaginatedpythonPythonPublicationResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedpythonPythonPublicationResponseListWithDefaults() *PaginatedpythonPythonPublicationResponseList {
	this := PaginatedpythonPythonPublicationResponseList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedpythonPythonPublicationResponseList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedpythonPythonPublicationResponseList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedpythonPythonPublicationResponseList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedpythonPythonPublicationResponseList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedpythonPythonPublicationResponseList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedpythonPythonPublicationResponseList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedpythonPythonPublicationResponseList) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedpythonPythonPublicationResponseList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedpythonPythonPublicationResponseList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedpythonPythonPublicationResponseList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedpythonPythonPublicationResponseList) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value
func (o *PaginatedpythonPythonPublicationResponseList) GetResults() []PythonPythonPublicationResponse {
	if o == nil {
		var ret []PythonPythonPublicationResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedpythonPythonPublicationResponseList) GetResultsOk() ([]PythonPythonPublicationResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedpythonPythonPublicationResponseList) SetResults(v []PythonPythonPublicationResponse) {
	o.Results = v
}

func (o PaginatedpythonPythonPublicationResponseList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedpythonPythonPublicationResponseList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedpythonPythonPublicationResponseList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedpythonPythonPublicationResponseList := _PaginatedpythonPythonPublicationResponseList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedpythonPythonPublicationResponseList)

	if err != nil {
		return err
	}

	*o = PaginatedpythonPythonPublicationResponseList(varPaginatedpythonPythonPublicationResponseList)

	return err
}

type NullablePaginatedpythonPythonPublicationResponseList struct {
	value *PaginatedpythonPythonPublicationResponseList
	isSet bool
}

func (v NullablePaginatedpythonPythonPublicationResponseList) Get() *PaginatedpythonPythonPublicationResponseList {
	return v.value
}

func (v *NullablePaginatedpythonPythonPublicationResponseList) Set(val *PaginatedpythonPythonPublicationResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedpythonPythonPublicationResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedpythonPythonPublicationResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedpythonPythonPublicationResponseList(val *PaginatedpythonPythonPublicationResponseList) *NullablePaginatedpythonPythonPublicationResponseList {
	return &NullablePaginatedpythonPythonPublicationResponseList{value: val, isSet: true}
}

func (v NullablePaginatedpythonPythonPublicationResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedpythonPythonPublicationResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


