/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"fmt"
)

// checks if the ServiceFeatureContentGuard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceFeatureContentGuard{}

// ServiceFeatureContentGuard A serializer for FeatureContentGuard.
type ServiceFeatureContentGuard struct {
	// The unique name.
	Name string `json:"name"`
	// An optional description.
	Description *string `json:"description,omitempty"`
	HeaderName string `json:"header_name"`
	JqFilter *string `json:"jq_filter,omitempty"`
	// The list of features required to access the content.
	Features []string `json:"features"`
	AdditionalProperties map[string]interface{}
}

type _ServiceFeatureContentGuard ServiceFeatureContentGuard

// NewServiceFeatureContentGuard instantiates a new ServiceFeatureContentGuard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceFeatureContentGuard(name string, headerName string, features []string) *ServiceFeatureContentGuard {
	this := ServiceFeatureContentGuard{}
	this.Name = name
	this.HeaderName = headerName
	this.Features = features
	return &this
}

// NewServiceFeatureContentGuardWithDefaults instantiates a new ServiceFeatureContentGuard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceFeatureContentGuardWithDefaults() *ServiceFeatureContentGuard {
	this := ServiceFeatureContentGuard{}
	return &this
}

// GetName returns the Name field value
func (o *ServiceFeatureContentGuard) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceFeatureContentGuard) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceFeatureContentGuard) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServiceFeatureContentGuard) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceFeatureContentGuard) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServiceFeatureContentGuard) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServiceFeatureContentGuard) SetDescription(v string) {
	o.Description = &v
}

// GetHeaderName returns the HeaderName field value
func (o *ServiceFeatureContentGuard) GetHeaderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HeaderName
}

// GetHeaderNameOk returns a tuple with the HeaderName field value
// and a boolean to check if the value has been set.
func (o *ServiceFeatureContentGuard) GetHeaderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeaderName, true
}

// SetHeaderName sets field value
func (o *ServiceFeatureContentGuard) SetHeaderName(v string) {
	o.HeaderName = v
}

// GetJqFilter returns the JqFilter field value if set, zero value otherwise.
func (o *ServiceFeatureContentGuard) GetJqFilter() string {
	if o == nil || IsNil(o.JqFilter) {
		var ret string
		return ret
	}
	return *o.JqFilter
}

// GetJqFilterOk returns a tuple with the JqFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceFeatureContentGuard) GetJqFilterOk() (*string, bool) {
	if o == nil || IsNil(o.JqFilter) {
		return nil, false
	}
	return o.JqFilter, true
}

// HasJqFilter returns a boolean if a field has been set.
func (o *ServiceFeatureContentGuard) HasJqFilter() bool {
	if o != nil && !IsNil(o.JqFilter) {
		return true
	}

	return false
}

// SetJqFilter gets a reference to the given string and assigns it to the JqFilter field.
func (o *ServiceFeatureContentGuard) SetJqFilter(v string) {
	o.JqFilter = &v
}

// GetFeatures returns the Features field value
func (o *ServiceFeatureContentGuard) GetFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *ServiceFeatureContentGuard) GetFeaturesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *ServiceFeatureContentGuard) SetFeatures(v []string) {
	o.Features = v
}

func (o ServiceFeatureContentGuard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceFeatureContentGuard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["header_name"] = o.HeaderName
	if !IsNil(o.JqFilter) {
		toSerialize["jq_filter"] = o.JqFilter
	}
	toSerialize["features"] = o.Features

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceFeatureContentGuard) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"header_name",
		"features",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceFeatureContentGuard := _ServiceFeatureContentGuard{}

	err = json.Unmarshal(data, &varServiceFeatureContentGuard)

	if err != nil {
		return err
	}

	*o = ServiceFeatureContentGuard(varServiceFeatureContentGuard)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "header_name")
		delete(additionalProperties, "jq_filter")
		delete(additionalProperties, "features")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceFeatureContentGuard struct {
	value *ServiceFeatureContentGuard
	isSet bool
}

func (v NullableServiceFeatureContentGuard) Get() *ServiceFeatureContentGuard {
	return v.value
}

func (v *NullableServiceFeatureContentGuard) Set(val *ServiceFeatureContentGuard) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceFeatureContentGuard) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceFeatureContentGuard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceFeatureContentGuard(val *ServiceFeatureContentGuard) *NullableServiceFeatureContentGuard {
	return &NullableServiceFeatureContentGuard{value: val, isSet: true}
}

func (v NullableServiceFeatureContentGuard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceFeatureContentGuard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


