/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedrpmPackageGroupResponseList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedrpmPackageGroupResponseList{}

// PaginatedrpmPackageGroupResponseList struct for PaginatedrpmPackageGroupResponseList
type PaginatedrpmPackageGroupResponseList struct {
	Count int32 `json:"count"`
	Next *string `json:"next,omitempty"`
	Previous *string `json:"previous,omitempty"`
	Results []RpmPackageGroupResponse `json:"results"`
}

type _PaginatedrpmPackageGroupResponseList PaginatedrpmPackageGroupResponseList

// NewPaginatedrpmPackageGroupResponseList instantiates a new PaginatedrpmPackageGroupResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedrpmPackageGroupResponseList(count int32, results []RpmPackageGroupResponse) *PaginatedrpmPackageGroupResponseList {
	this := PaginatedrpmPackageGroupResponseList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedrpmPackageGroupResponseListWithDefaults instantiates a new PaginatedrpmPackageGroupResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedrpmPackageGroupResponseListWithDefaults() *PaginatedrpmPackageGroupResponseList {
	this := PaginatedrpmPackageGroupResponseList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedrpmPackageGroupResponseList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedrpmPackageGroupResponseList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedrpmPackageGroupResponseList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedrpmPackageGroupResponseList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedrpmPackageGroupResponseList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedrpmPackageGroupResponseList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedrpmPackageGroupResponseList) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedrpmPackageGroupResponseList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedrpmPackageGroupResponseList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedrpmPackageGroupResponseList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedrpmPackageGroupResponseList) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value
func (o *PaginatedrpmPackageGroupResponseList) GetResults() []RpmPackageGroupResponse {
	if o == nil {
		var ret []RpmPackageGroupResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedrpmPackageGroupResponseList) GetResultsOk() ([]RpmPackageGroupResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedrpmPackageGroupResponseList) SetResults(v []RpmPackageGroupResponse) {
	o.Results = v
}

func (o PaginatedrpmPackageGroupResponseList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedrpmPackageGroupResponseList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedrpmPackageGroupResponseList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedrpmPackageGroupResponseList := _PaginatedrpmPackageGroupResponseList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedrpmPackageGroupResponseList)

	if err != nil {
		return err
	}

	*o = PaginatedrpmPackageGroupResponseList(varPaginatedrpmPackageGroupResponseList)

	return err
}

type NullablePaginatedrpmPackageGroupResponseList struct {
	value *PaginatedrpmPackageGroupResponseList
	isSet bool
}

func (v NullablePaginatedrpmPackageGroupResponseList) Get() *PaginatedrpmPackageGroupResponseList {
	return v.value
}

func (v *NullablePaginatedrpmPackageGroupResponseList) Set(val *PaginatedrpmPackageGroupResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedrpmPackageGroupResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedrpmPackageGroupResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedrpmPackageGroupResponseList(val *PaginatedrpmPackageGroupResponseList) *NullablePaginatedrpmPackageGroupResponseList {
	return &NullablePaginatedrpmPackageGroupResponseList{value: val, isSet: true}
}

func (v NullablePaginatedrpmPackageGroupResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedrpmPackageGroupResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


