/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedTaskResponseList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedTaskResponseList{}

// PaginatedTaskResponseList struct for PaginatedTaskResponseList
type PaginatedTaskResponseList struct {
	Count int32 `json:"count"`
	Next *string `json:"next,omitempty"`
	Previous *string `json:"previous,omitempty"`
	Results []TaskResponse `json:"results"`
}

type _PaginatedTaskResponseList PaginatedTaskResponseList

// NewPaginatedTaskResponseList instantiates a new PaginatedTaskResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedTaskResponseList(count int32, results []TaskResponse) *PaginatedTaskResponseList {
	this := PaginatedTaskResponseList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedTaskResponseListWithDefaults instantiates a new PaginatedTaskResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedTaskResponseListWithDefaults() *PaginatedTaskResponseList {
	this := PaginatedTaskResponseList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedTaskResponseList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedTaskResponseList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedTaskResponseList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedTaskResponseList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedTaskResponseList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedTaskResponseList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedTaskResponseList) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedTaskResponseList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedTaskResponseList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedTaskResponseList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedTaskResponseList) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value
func (o *PaginatedTaskResponseList) GetResults() []TaskResponse {
	if o == nil {
		var ret []TaskResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedTaskResponseList) GetResultsOk() ([]TaskResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedTaskResponseList) SetResults(v []TaskResponse) {
	o.Results = v
}

func (o PaginatedTaskResponseList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedTaskResponseList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedTaskResponseList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedTaskResponseList := _PaginatedTaskResponseList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedTaskResponseList)

	if err != nil {
		return err
	}

	*o = PaginatedTaskResponseList(varPaginatedTaskResponseList)

	return err
}

type NullablePaginatedTaskResponseList struct {
	value *PaginatedTaskResponseList
	isSet bool
}

func (v NullablePaginatedTaskResponseList) Get() *PaginatedTaskResponseList {
	return v.value
}

func (v *NullablePaginatedTaskResponseList) Set(val *PaginatedTaskResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedTaskResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedTaskResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedTaskResponseList(val *PaginatedTaskResponseList) *NullablePaginatedTaskResponseList {
	return &NullablePaginatedTaskResponseList{value: val, isSet: true}
}

func (v NullablePaginatedTaskResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedTaskResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


