/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"fmt"
)

// checks if the PythonPythonRemote type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PythonPythonRemote{}

// PythonPythonRemote A Serializer for PythonRemote.
type PythonPythonRemote struct {
	// A unique name for this remote.
	Name string `json:"name"`
	// The URL of an external content source.
	Url string `json:"url"`
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
	// The policy to use when downloading content. The possible values include: 'immediate', 'on_demand', and 'streamed'. 'on_demand' is the default.* `immediate` - When syncing, download all metadata and content now.* `on_demand` - When syncing, download metadata, but do not download content now. Instead, download content as clients request it, and save it in Pulp to be served for future client requests.* `streamed` - When syncing, download metadata, but do not download content now. Instead,download content as clients request it, but never save it in Pulp. This causes future requests for that same content to have to be downloaded again.
	Policy *Policy692Enum `json:"policy,omitempty"`
	// A PEM encoded CA certificate used to validate the server certificate presented by the remote server.
	CaCert *string `json:"ca_cert,omitempty"`
	// A PEM encoded client certificate used for authentication.
	ClientCert *string `json:"client_cert,omitempty"`
	// A PEM encoded private key used for authentication.
	ClientKey *string `json:"client_key,omitempty"`
	// If True, TLS peer validation must be performed.
	TlsValidation *bool `json:"tls_validation,omitempty"`
	// The proxy URL. Format: scheme://host:port
	ProxyUrl *string `json:"proxy_url,omitempty"`
	// The username to authenticte to the proxy.
	ProxyUsername *string `json:"proxy_username,omitempty"`
	// The password to authenticate to the proxy. Extra leading and trailing whitespace characters are not trimmed.
	ProxyPassword *string `json:"proxy_password,omitempty"`
	// The username to be used for authentication when syncing.
	Username *string `json:"username,omitempty"`
	// The password to be used for authentication when syncing. Extra leading and trailing whitespace characters are not trimmed.
	Password *string `json:"password,omitempty"`
	// Maximum number of retry attempts after a download failure. If not set then the default value (3) will be used.
	MaxRetries *int64 `json:"max_retries,omitempty"`
	// aiohttp.ClientTimeout.total (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	TotalTimeout *float64 `json:"total_timeout,omitempty"`
	// aiohttp.ClientTimeout.connect (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	ConnectTimeout *float64 `json:"connect_timeout,omitempty"`
	// aiohttp.ClientTimeout.sock_connect (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	SockConnectTimeout *float64 `json:"sock_connect_timeout,omitempty"`
	// aiohttp.ClientTimeout.sock_read (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	SockReadTimeout *float64 `json:"sock_read_timeout,omitempty"`
	// Headers for aiohttp.Clientsession
	Headers []map[string]interface{} `json:"headers,omitempty"`
	// Total number of simultaneous connections. If not set then the default value will be used.
	DownloadConcurrency *int64 `json:"download_concurrency,omitempty"`
	// Limits requests per second for each concurrent downloader
	RateLimit *int64 `json:"rate_limit,omitempty"`
	// A list containing project specifiers for Python packages to include.
	Includes []string `json:"includes,omitempty"`
	// A list containing project specifiers for Python packages to exclude.
	Excludes []string `json:"excludes,omitempty"`
	// Whether or not to include pre-release packages in the sync.
	Prereleases *bool `json:"prereleases,omitempty"`
	// The package types to sync for Python content. Leave blank to get everypackage type.
	PackageTypes []PackageTypesEnum `json:"package_types,omitempty"`
	// The amount of latest versions of a package to keep on sync, includespre-releases if synced. Default 0 keeps all versions.
	KeepLatestPackages *int64 `json:"keep_latest_packages,omitempty"`
	// List of platforms to exclude syncing Python packages for. Possible valuesinclude: windows, macos, freebsd, and linux.
	ExcludePlatforms []ExcludePlatformsEnum `json:"exclude_platforms,omitempty"`
	// Whether to sync available provenances for Python packages.
	Provenance *bool `json:"provenance,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PythonPythonRemote PythonPythonRemote

// NewPythonPythonRemote instantiates a new PythonPythonRemote object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPythonPythonRemote(name string, url string) *PythonPythonRemote {
	this := PythonPythonRemote{}
	this.Name = name
	this.Url = url
	var policy Policy692Enum = POLICY692ENUM_ON_DEMAND
	this.Policy = &policy
	var keepLatestPackages int64 = 0
	this.KeepLatestPackages = &keepLatestPackages
	var provenance bool = false
	this.Provenance = &provenance
	return &this
}

// NewPythonPythonRemoteWithDefaults instantiates a new PythonPythonRemote object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPythonPythonRemoteWithDefaults() *PythonPythonRemote {
	this := PythonPythonRemote{}
	var policy Policy692Enum = POLICY692ENUM_ON_DEMAND
	this.Policy = &policy
	var keepLatestPackages int64 = 0
	this.KeepLatestPackages = &keepLatestPackages
	var provenance bool = false
	this.Provenance = &provenance
	return &this
}

// GetName returns the Name field value
func (o *PythonPythonRemote) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PythonPythonRemote) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *PythonPythonRemote) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PythonPythonRemote) SetUrl(v string) {
	o.Url = v
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *PythonPythonRemote) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetPolicy() Policy692Enum {
	if o == nil || IsNil(o.Policy) {
		var ret Policy692Enum
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetPolicyOk() (*Policy692Enum, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given Policy692Enum and assigns it to the Policy field.
func (o *PythonPythonRemote) SetPolicy(v Policy692Enum) {
	o.Policy = &v
}

// GetCaCert returns the CaCert field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetCaCert() string {
	if o == nil || IsNil(o.CaCert) {
		var ret string
		return ret
	}
	return *o.CaCert
}

// GetCaCertOk returns a tuple with the CaCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetCaCertOk() (*string, bool) {
	if o == nil || IsNil(o.CaCert) {
		return nil, false
	}
	return o.CaCert, true
}

// HasCaCert returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasCaCert() bool {
	if o != nil && !IsNil(o.CaCert) {
		return true
	}

	return false
}

// SetCaCert gets a reference to the given string and assigns it to the CaCert field.
func (o *PythonPythonRemote) SetCaCert(v string) {
	o.CaCert = &v
}

// GetClientCert returns the ClientCert field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetClientCert() string {
	if o == nil || IsNil(o.ClientCert) {
		var ret string
		return ret
	}
	return *o.ClientCert
}

// GetClientCertOk returns a tuple with the ClientCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetClientCertOk() (*string, bool) {
	if o == nil || IsNil(o.ClientCert) {
		return nil, false
	}
	return o.ClientCert, true
}

// HasClientCert returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasClientCert() bool {
	if o != nil && !IsNil(o.ClientCert) {
		return true
	}

	return false
}

// SetClientCert gets a reference to the given string and assigns it to the ClientCert field.
func (o *PythonPythonRemote) SetClientCert(v string) {
	o.ClientCert = &v
}

// GetClientKey returns the ClientKey field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetClientKey() string {
	if o == nil || IsNil(o.ClientKey) {
		var ret string
		return ret
	}
	return *o.ClientKey
}

// GetClientKeyOk returns a tuple with the ClientKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetClientKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ClientKey) {
		return nil, false
	}
	return o.ClientKey, true
}

// HasClientKey returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasClientKey() bool {
	if o != nil && !IsNil(o.ClientKey) {
		return true
	}

	return false
}

// SetClientKey gets a reference to the given string and assigns it to the ClientKey field.
func (o *PythonPythonRemote) SetClientKey(v string) {
	o.ClientKey = &v
}

// GetTlsValidation returns the TlsValidation field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetTlsValidation() bool {
	if o == nil || IsNil(o.TlsValidation) {
		var ret bool
		return ret
	}
	return *o.TlsValidation
}

// GetTlsValidationOk returns a tuple with the TlsValidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetTlsValidationOk() (*bool, bool) {
	if o == nil || IsNil(o.TlsValidation) {
		return nil, false
	}
	return o.TlsValidation, true
}

// HasTlsValidation returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasTlsValidation() bool {
	if o != nil && !IsNil(o.TlsValidation) {
		return true
	}

	return false
}

// SetTlsValidation gets a reference to the given bool and assigns it to the TlsValidation field.
func (o *PythonPythonRemote) SetTlsValidation(v bool) {
	o.TlsValidation = &v
}

// GetProxyUrl returns the ProxyUrl field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetProxyUrl() string {
	if o == nil || IsNil(o.ProxyUrl) {
		var ret string
		return ret
	}
	return *o.ProxyUrl
}

// GetProxyUrlOk returns a tuple with the ProxyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetProxyUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyUrl) {
		return nil, false
	}
	return o.ProxyUrl, true
}

// HasProxyUrl returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasProxyUrl() bool {
	if o != nil && !IsNil(o.ProxyUrl) {
		return true
	}

	return false
}

// SetProxyUrl gets a reference to the given string and assigns it to the ProxyUrl field.
func (o *PythonPythonRemote) SetProxyUrl(v string) {
	o.ProxyUrl = &v
}

// GetProxyUsername returns the ProxyUsername field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetProxyUsername() string {
	if o == nil || IsNil(o.ProxyUsername) {
		var ret string
		return ret
	}
	return *o.ProxyUsername
}

// GetProxyUsernameOk returns a tuple with the ProxyUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetProxyUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyUsername) {
		return nil, false
	}
	return o.ProxyUsername, true
}

// HasProxyUsername returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasProxyUsername() bool {
	if o != nil && !IsNil(o.ProxyUsername) {
		return true
	}

	return false
}

// SetProxyUsername gets a reference to the given string and assigns it to the ProxyUsername field.
func (o *PythonPythonRemote) SetProxyUsername(v string) {
	o.ProxyUsername = &v
}

// GetProxyPassword returns the ProxyPassword field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetProxyPassword() string {
	if o == nil || IsNil(o.ProxyPassword) {
		var ret string
		return ret
	}
	return *o.ProxyPassword
}

// GetProxyPasswordOk returns a tuple with the ProxyPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetProxyPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyPassword) {
		return nil, false
	}
	return o.ProxyPassword, true
}

// HasProxyPassword returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasProxyPassword() bool {
	if o != nil && !IsNil(o.ProxyPassword) {
		return true
	}

	return false
}

// SetProxyPassword gets a reference to the given string and assigns it to the ProxyPassword field.
func (o *PythonPythonRemote) SetProxyPassword(v string) {
	o.ProxyPassword = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *PythonPythonRemote) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *PythonPythonRemote) SetPassword(v string) {
	o.Password = &v
}

// GetMaxRetries returns the MaxRetries field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetMaxRetries() int64 {
	if o == nil || IsNil(o.MaxRetries) {
		var ret int64
		return ret
	}
	return *o.MaxRetries
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetMaxRetriesOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxRetries) {
		return nil, false
	}
	return o.MaxRetries, true
}

// HasMaxRetries returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasMaxRetries() bool {
	if o != nil && !IsNil(o.MaxRetries) {
		return true
	}

	return false
}

// SetMaxRetries gets a reference to the given int64 and assigns it to the MaxRetries field.
func (o *PythonPythonRemote) SetMaxRetries(v int64) {
	o.MaxRetries = &v
}

// GetTotalTimeout returns the TotalTimeout field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetTotalTimeout() float64 {
	if o == nil || IsNil(o.TotalTimeout) {
		var ret float64
		return ret
	}
	return *o.TotalTimeout
}

// GetTotalTimeoutOk returns a tuple with the TotalTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetTotalTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalTimeout) {
		return nil, false
	}
	return o.TotalTimeout, true
}

// HasTotalTimeout returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasTotalTimeout() bool {
	if o != nil && !IsNil(o.TotalTimeout) {
		return true
	}

	return false
}

// SetTotalTimeout gets a reference to the given float64 and assigns it to the TotalTimeout field.
func (o *PythonPythonRemote) SetTotalTimeout(v float64) {
	o.TotalTimeout = &v
}

// GetConnectTimeout returns the ConnectTimeout field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetConnectTimeout() float64 {
	if o == nil || IsNil(o.ConnectTimeout) {
		var ret float64
		return ret
	}
	return *o.ConnectTimeout
}

// GetConnectTimeoutOk returns a tuple with the ConnectTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetConnectTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.ConnectTimeout) {
		return nil, false
	}
	return o.ConnectTimeout, true
}

// HasConnectTimeout returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasConnectTimeout() bool {
	if o != nil && !IsNil(o.ConnectTimeout) {
		return true
	}

	return false
}

// SetConnectTimeout gets a reference to the given float64 and assigns it to the ConnectTimeout field.
func (o *PythonPythonRemote) SetConnectTimeout(v float64) {
	o.ConnectTimeout = &v
}

// GetSockConnectTimeout returns the SockConnectTimeout field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetSockConnectTimeout() float64 {
	if o == nil || IsNil(o.SockConnectTimeout) {
		var ret float64
		return ret
	}
	return *o.SockConnectTimeout
}

// GetSockConnectTimeoutOk returns a tuple with the SockConnectTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetSockConnectTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.SockConnectTimeout) {
		return nil, false
	}
	return o.SockConnectTimeout, true
}

// HasSockConnectTimeout returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasSockConnectTimeout() bool {
	if o != nil && !IsNil(o.SockConnectTimeout) {
		return true
	}

	return false
}

// SetSockConnectTimeout gets a reference to the given float64 and assigns it to the SockConnectTimeout field.
func (o *PythonPythonRemote) SetSockConnectTimeout(v float64) {
	o.SockConnectTimeout = &v
}

// GetSockReadTimeout returns the SockReadTimeout field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetSockReadTimeout() float64 {
	if o == nil || IsNil(o.SockReadTimeout) {
		var ret float64
		return ret
	}
	return *o.SockReadTimeout
}

// GetSockReadTimeoutOk returns a tuple with the SockReadTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetSockReadTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.SockReadTimeout) {
		return nil, false
	}
	return o.SockReadTimeout, true
}

// HasSockReadTimeout returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasSockReadTimeout() bool {
	if o != nil && !IsNil(o.SockReadTimeout) {
		return true
	}

	return false
}

// SetSockReadTimeout gets a reference to the given float64 and assigns it to the SockReadTimeout field.
func (o *PythonPythonRemote) SetSockReadTimeout(v float64) {
	o.SockReadTimeout = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetHeaders() []map[string]interface{} {
	if o == nil || IsNil(o.Headers) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetHeadersOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []map[string]interface{} and assigns it to the Headers field.
func (o *PythonPythonRemote) SetHeaders(v []map[string]interface{}) {
	o.Headers = v
}

// GetDownloadConcurrency returns the DownloadConcurrency field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetDownloadConcurrency() int64 {
	if o == nil || IsNil(o.DownloadConcurrency) {
		var ret int64
		return ret
	}
	return *o.DownloadConcurrency
}

// GetDownloadConcurrencyOk returns a tuple with the DownloadConcurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetDownloadConcurrencyOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadConcurrency) {
		return nil, false
	}
	return o.DownloadConcurrency, true
}

// HasDownloadConcurrency returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasDownloadConcurrency() bool {
	if o != nil && !IsNil(o.DownloadConcurrency) {
		return true
	}

	return false
}

// SetDownloadConcurrency gets a reference to the given int64 and assigns it to the DownloadConcurrency field.
func (o *PythonPythonRemote) SetDownloadConcurrency(v int64) {
	o.DownloadConcurrency = &v
}

// GetRateLimit returns the RateLimit field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetRateLimit() int64 {
	if o == nil || IsNil(o.RateLimit) {
		var ret int64
		return ret
	}
	return *o.RateLimit
}

// GetRateLimitOk returns a tuple with the RateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetRateLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.RateLimit) {
		return nil, false
	}
	return o.RateLimit, true
}

// HasRateLimit returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasRateLimit() bool {
	if o != nil && !IsNil(o.RateLimit) {
		return true
	}

	return false
}

// SetRateLimit gets a reference to the given int64 and assigns it to the RateLimit field.
func (o *PythonPythonRemote) SetRateLimit(v int64) {
	o.RateLimit = &v
}

// GetIncludes returns the Includes field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetIncludes() []string {
	if o == nil || IsNil(o.Includes) {
		var ret []string
		return ret
	}
	return o.Includes
}

// GetIncludesOk returns a tuple with the Includes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetIncludesOk() ([]string, bool) {
	if o == nil || IsNil(o.Includes) {
		return nil, false
	}
	return o.Includes, true
}

// HasIncludes returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasIncludes() bool {
	if o != nil && !IsNil(o.Includes) {
		return true
	}

	return false
}

// SetIncludes gets a reference to the given []string and assigns it to the Includes field.
func (o *PythonPythonRemote) SetIncludes(v []string) {
	o.Includes = v
}

// GetExcludes returns the Excludes field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetExcludes() []string {
	if o == nil || IsNil(o.Excludes) {
		var ret []string
		return ret
	}
	return o.Excludes
}

// GetExcludesOk returns a tuple with the Excludes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetExcludesOk() ([]string, bool) {
	if o == nil || IsNil(o.Excludes) {
		return nil, false
	}
	return o.Excludes, true
}

// HasExcludes returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasExcludes() bool {
	if o != nil && !IsNil(o.Excludes) {
		return true
	}

	return false
}

// SetExcludes gets a reference to the given []string and assigns it to the Excludes field.
func (o *PythonPythonRemote) SetExcludes(v []string) {
	o.Excludes = v
}

// GetPrereleases returns the Prereleases field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetPrereleases() bool {
	if o == nil || IsNil(o.Prereleases) {
		var ret bool
		return ret
	}
	return *o.Prereleases
}

// GetPrereleasesOk returns a tuple with the Prereleases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetPrereleasesOk() (*bool, bool) {
	if o == nil || IsNil(o.Prereleases) {
		return nil, false
	}
	return o.Prereleases, true
}

// HasPrereleases returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasPrereleases() bool {
	if o != nil && !IsNil(o.Prereleases) {
		return true
	}

	return false
}

// SetPrereleases gets a reference to the given bool and assigns it to the Prereleases field.
func (o *PythonPythonRemote) SetPrereleases(v bool) {
	o.Prereleases = &v
}

// GetPackageTypes returns the PackageTypes field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetPackageTypes() []PackageTypesEnum {
	if o == nil || IsNil(o.PackageTypes) {
		var ret []PackageTypesEnum
		return ret
	}
	return o.PackageTypes
}

// GetPackageTypesOk returns a tuple with the PackageTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetPackageTypesOk() ([]PackageTypesEnum, bool) {
	if o == nil || IsNil(o.PackageTypes) {
		return nil, false
	}
	return o.PackageTypes, true
}

// HasPackageTypes returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasPackageTypes() bool {
	if o != nil && !IsNil(o.PackageTypes) {
		return true
	}

	return false
}

// SetPackageTypes gets a reference to the given []PackageTypesEnum and assigns it to the PackageTypes field.
func (o *PythonPythonRemote) SetPackageTypes(v []PackageTypesEnum) {
	o.PackageTypes = v
}

// GetKeepLatestPackages returns the KeepLatestPackages field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetKeepLatestPackages() int64 {
	if o == nil || IsNil(o.KeepLatestPackages) {
		var ret int64
		return ret
	}
	return *o.KeepLatestPackages
}

// GetKeepLatestPackagesOk returns a tuple with the KeepLatestPackages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetKeepLatestPackagesOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepLatestPackages) {
		return nil, false
	}
	return o.KeepLatestPackages, true
}

// HasKeepLatestPackages returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasKeepLatestPackages() bool {
	if o != nil && !IsNil(o.KeepLatestPackages) {
		return true
	}

	return false
}

// SetKeepLatestPackages gets a reference to the given int64 and assigns it to the KeepLatestPackages field.
func (o *PythonPythonRemote) SetKeepLatestPackages(v int64) {
	o.KeepLatestPackages = &v
}

// GetExcludePlatforms returns the ExcludePlatforms field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetExcludePlatforms() []ExcludePlatformsEnum {
	if o == nil || IsNil(o.ExcludePlatforms) {
		var ret []ExcludePlatformsEnum
		return ret
	}
	return o.ExcludePlatforms
}

// GetExcludePlatformsOk returns a tuple with the ExcludePlatforms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetExcludePlatformsOk() ([]ExcludePlatformsEnum, bool) {
	if o == nil || IsNil(o.ExcludePlatforms) {
		return nil, false
	}
	return o.ExcludePlatforms, true
}

// HasExcludePlatforms returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasExcludePlatforms() bool {
	if o != nil && !IsNil(o.ExcludePlatforms) {
		return true
	}

	return false
}

// SetExcludePlatforms gets a reference to the given []ExcludePlatformsEnum and assigns it to the ExcludePlatforms field.
func (o *PythonPythonRemote) SetExcludePlatforms(v []ExcludePlatformsEnum) {
	o.ExcludePlatforms = v
}

// GetProvenance returns the Provenance field value if set, zero value otherwise.
func (o *PythonPythonRemote) GetProvenance() bool {
	if o == nil || IsNil(o.Provenance) {
		var ret bool
		return ret
	}
	return *o.Provenance
}

// GetProvenanceOk returns a tuple with the Provenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PythonPythonRemote) GetProvenanceOk() (*bool, bool) {
	if o == nil || IsNil(o.Provenance) {
		return nil, false
	}
	return o.Provenance, true
}

// HasProvenance returns a boolean if a field has been set.
func (o *PythonPythonRemote) HasProvenance() bool {
	if o != nil && !IsNil(o.Provenance) {
		return true
	}

	return false
}

// SetProvenance gets a reference to the given bool and assigns it to the Provenance field.
func (o *PythonPythonRemote) SetProvenance(v bool) {
	o.Provenance = &v
}

func (o PythonPythonRemote) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PythonPythonRemote) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.CaCert) {
		toSerialize["ca_cert"] = o.CaCert
	}
	if !IsNil(o.ClientCert) {
		toSerialize["client_cert"] = o.ClientCert
	}
	if !IsNil(o.ClientKey) {
		toSerialize["client_key"] = o.ClientKey
	}
	if !IsNil(o.TlsValidation) {
		toSerialize["tls_validation"] = o.TlsValidation
	}
	if !IsNil(o.ProxyUrl) {
		toSerialize["proxy_url"] = o.ProxyUrl
	}
	if !IsNil(o.ProxyUsername) {
		toSerialize["proxy_username"] = o.ProxyUsername
	}
	if !IsNil(o.ProxyPassword) {
		toSerialize["proxy_password"] = o.ProxyPassword
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.MaxRetries) {
		toSerialize["max_retries"] = o.MaxRetries
	}
	if !IsNil(o.TotalTimeout) {
		toSerialize["total_timeout"] = o.TotalTimeout
	}
	if !IsNil(o.ConnectTimeout) {
		toSerialize["connect_timeout"] = o.ConnectTimeout
	}
	if !IsNil(o.SockConnectTimeout) {
		toSerialize["sock_connect_timeout"] = o.SockConnectTimeout
	}
	if !IsNil(o.SockReadTimeout) {
		toSerialize["sock_read_timeout"] = o.SockReadTimeout
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.DownloadConcurrency) {
		toSerialize["download_concurrency"] = o.DownloadConcurrency
	}
	if !IsNil(o.RateLimit) {
		toSerialize["rate_limit"] = o.RateLimit
	}
	if !IsNil(o.Includes) {
		toSerialize["includes"] = o.Includes
	}
	if !IsNil(o.Excludes) {
		toSerialize["excludes"] = o.Excludes
	}
	if !IsNil(o.Prereleases) {
		toSerialize["prereleases"] = o.Prereleases
	}
	if !IsNil(o.PackageTypes) {
		toSerialize["package_types"] = o.PackageTypes
	}
	if !IsNil(o.KeepLatestPackages) {
		toSerialize["keep_latest_packages"] = o.KeepLatestPackages
	}
	if !IsNil(o.ExcludePlatforms) {
		toSerialize["exclude_platforms"] = o.ExcludePlatforms
	}
	if !IsNil(o.Provenance) {
		toSerialize["provenance"] = o.Provenance
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PythonPythonRemote) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPythonPythonRemote := _PythonPythonRemote{}

	err = json.Unmarshal(data, &varPythonPythonRemote)

	if err != nil {
		return err
	}

	*o = PythonPythonRemote(varPythonPythonRemote)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "url")
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "policy")
		delete(additionalProperties, "ca_cert")
		delete(additionalProperties, "client_cert")
		delete(additionalProperties, "client_key")
		delete(additionalProperties, "tls_validation")
		delete(additionalProperties, "proxy_url")
		delete(additionalProperties, "proxy_username")
		delete(additionalProperties, "proxy_password")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		delete(additionalProperties, "max_retries")
		delete(additionalProperties, "total_timeout")
		delete(additionalProperties, "connect_timeout")
		delete(additionalProperties, "sock_connect_timeout")
		delete(additionalProperties, "sock_read_timeout")
		delete(additionalProperties, "headers")
		delete(additionalProperties, "download_concurrency")
		delete(additionalProperties, "rate_limit")
		delete(additionalProperties, "includes")
		delete(additionalProperties, "excludes")
		delete(additionalProperties, "prereleases")
		delete(additionalProperties, "package_types")
		delete(additionalProperties, "keep_latest_packages")
		delete(additionalProperties, "exclude_platforms")
		delete(additionalProperties, "provenance")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePythonPythonRemote struct {
	value *PythonPythonRemote
	isSet bool
}

func (v NullablePythonPythonRemote) Get() *PythonPythonRemote {
	return v.value
}

func (v *NullablePythonPythonRemote) Set(val *PythonPythonRemote) {
	v.value = val
	v.isSet = true
}

func (v NullablePythonPythonRemote) IsSet() bool {
	return v.isSet
}

func (v *NullablePythonPythonRemote) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePythonPythonRemote(val *PythonPythonRemote) *NullablePythonPythonRemote {
	return &NullablePythonPythonRemote{value: val, isSet: true}
}

func (v NullablePythonPythonRemote) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePythonPythonRemote) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


