/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HuggingFaceHuggingFaceRemoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HuggingFaceHuggingFaceRemoteResponse{}

// HuggingFaceHuggingFaceRemoteResponse A Serializer for HuggingFaceRemote with Hugging Face specific configuration.
type HuggingFaceHuggingFaceRemoteResponse struct {
	PulpHref *string `json:"pulp_href,omitempty"`
	// The Pulp Resource Name (PRN).
	Prn *string `json:"prn,omitempty"`
	// Timestamp of creation.
	PulpCreated *time.Time `json:"pulp_created,omitempty"`
	// Timestamp of the most recent update of the remote.
	PulpLastUpdated *time.Time `json:"pulp_last_updated,omitempty"`
	// A unique name for this remote.
	Name string `json:"name"`
	// The URL of an external content source.
	Url string `json:"url"`
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
	// The policy to use when downloading content. The possible values include: 'immediate', 'on_demand', and 'streamed'. 'on_demand' enables pull-through caching.* `immediate` - When syncing, download all metadata and content now.* `on_demand` - When syncing, download metadata, but do not download content now. Instead, download content as clients request it, and save it in Pulp to be served for future client requests.* `streamed` - When syncing, download metadata, but do not download content now. Instead,download content as clients request it, but never save it in Pulp. This causes future requests for that same content to have to be downloaded again.
	Policy *Policy692Enum `json:"policy,omitempty"`
	// List of hidden (write only) fields
	HiddenFields []GenericRemoteResponseHiddenFieldsInner `json:"hidden_fields,omitempty"`
	// A PEM encoded CA certificate used to validate the server certificate presented by the remote server.
	CaCert *string `json:"ca_cert,omitempty"`
	// A PEM encoded client certificate used for authentication.
	ClientCert *string `json:"client_cert,omitempty"`
	// If True, TLS peer validation must be performed.
	TlsValidation *bool `json:"tls_validation,omitempty"`
	// The proxy URL. Format: scheme://host:port
	ProxyUrl *string `json:"proxy_url,omitempty"`
	// Maximum number of retry attempts after a download failure. If not set then the default value (3) will be used.
	MaxRetries *int64 `json:"max_retries,omitempty"`
	// aiohttp.ClientTimeout.total (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	TotalTimeout *float64 `json:"total_timeout,omitempty"`
	// aiohttp.ClientTimeout.connect (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	ConnectTimeout *float64 `json:"connect_timeout,omitempty"`
	// aiohttp.ClientTimeout.sock_connect (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	SockConnectTimeout *float64 `json:"sock_connect_timeout,omitempty"`
	// aiohttp.ClientTimeout.sock_read (q.v.) for download-connections. The default is null, which will cause the default from the aiohttp library to be used.
	SockReadTimeout *float64 `json:"sock_read_timeout,omitempty"`
	// Headers for aiohttp.Clientsession
	Headers []map[string]interface{} `json:"headers,omitempty"`
	// Total number of simultaneous connections. If not set then the default value will be used.
	DownloadConcurrency *int64 `json:"download_concurrency,omitempty"`
	// Limits requests per second for each concurrent downloader
	RateLimit *int64 `json:"rate_limit,omitempty"`
	// Base URL for Hugging Face Hub
	HfHubUrl *string `json:"hf_hub_url,omitempty"`
	// Hugging Face authentication token for private repositories
	HfToken *string `json:"hf_token,omitempty"`
}

type _HuggingFaceHuggingFaceRemoteResponse HuggingFaceHuggingFaceRemoteResponse

// NewHuggingFaceHuggingFaceRemoteResponse instantiates a new HuggingFaceHuggingFaceRemoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHuggingFaceHuggingFaceRemoteResponse(name string, url string) *HuggingFaceHuggingFaceRemoteResponse {
	this := HuggingFaceHuggingFaceRemoteResponse{}
	this.Name = name
	this.Url = url
	var policy Policy692Enum = POLICY692ENUM_ON_DEMAND
	this.Policy = &policy
	var hfHubUrl string = "https://huggingface.co"
	this.HfHubUrl = &hfHubUrl
	return &this
}

// NewHuggingFaceHuggingFaceRemoteResponseWithDefaults instantiates a new HuggingFaceHuggingFaceRemoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHuggingFaceHuggingFaceRemoteResponseWithDefaults() *HuggingFaceHuggingFaceRemoteResponse {
	this := HuggingFaceHuggingFaceRemoteResponse{}
	var policy Policy692Enum = POLICY692ENUM_ON_DEMAND
	this.Policy = &policy
	var hfHubUrl string = "https://huggingface.co"
	this.HfHubUrl = &hfHubUrl
	return &this
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPulpHref() string {
	if o == nil || IsNil(o.PulpHref) {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || IsNil(o.PulpHref) {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasPulpHref() bool {
	if o != nil && !IsNil(o.PulpHref) {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetPrn returns the Prn field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPrn() string {
	if o == nil || IsNil(o.Prn) {
		var ret string
		return ret
	}
	return *o.Prn
}

// GetPrnOk returns a tuple with the Prn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPrnOk() (*string, bool) {
	if o == nil || IsNil(o.Prn) {
		return nil, false
	}
	return o.Prn, true
}

// HasPrn returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasPrn() bool {
	if o != nil && !IsNil(o.Prn) {
		return true
	}

	return false
}

// SetPrn gets a reference to the given string and assigns it to the Prn field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetPrn(v string) {
	o.Prn = &v
}

// GetPulpCreated returns the PulpCreated field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPulpCreated() time.Time {
	if o == nil || IsNil(o.PulpCreated) {
		var ret time.Time
		return ret
	}
	return *o.PulpCreated
}

// GetPulpCreatedOk returns a tuple with the PulpCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPulpCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpCreated) {
		return nil, false
	}
	return o.PulpCreated, true
}

// HasPulpCreated returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasPulpCreated() bool {
	if o != nil && !IsNil(o.PulpCreated) {
		return true
	}

	return false
}

// SetPulpCreated gets a reference to the given time.Time and assigns it to the PulpCreated field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetPulpCreated(v time.Time) {
	o.PulpCreated = &v
}

// GetPulpLastUpdated returns the PulpLastUpdated field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPulpLastUpdated() time.Time {
	if o == nil || IsNil(o.PulpLastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.PulpLastUpdated
}

// GetPulpLastUpdatedOk returns a tuple with the PulpLastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPulpLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpLastUpdated) {
		return nil, false
	}
	return o.PulpLastUpdated, true
}

// HasPulpLastUpdated returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasPulpLastUpdated() bool {
	if o != nil && !IsNil(o.PulpLastUpdated) {
		return true
	}

	return false
}

// SetPulpLastUpdated gets a reference to the given time.Time and assigns it to the PulpLastUpdated field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetPulpLastUpdated(v time.Time) {
	o.PulpLastUpdated = &v
}

// GetName returns the Name field value
func (o *HuggingFaceHuggingFaceRemoteResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HuggingFaceHuggingFaceRemoteResponse) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *HuggingFaceHuggingFaceRemoteResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *HuggingFaceHuggingFaceRemoteResponse) SetUrl(v string) {
	o.Url = v
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPolicy() Policy692Enum {
	if o == nil || IsNil(o.Policy) {
		var ret Policy692Enum
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetPolicyOk() (*Policy692Enum, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given Policy692Enum and assigns it to the Policy field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetPolicy(v Policy692Enum) {
	o.Policy = &v
}

// GetHiddenFields returns the HiddenFields field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetHiddenFields() []GenericRemoteResponseHiddenFieldsInner {
	if o == nil || IsNil(o.HiddenFields) {
		var ret []GenericRemoteResponseHiddenFieldsInner
		return ret
	}
	return o.HiddenFields
}

// GetHiddenFieldsOk returns a tuple with the HiddenFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetHiddenFieldsOk() ([]GenericRemoteResponseHiddenFieldsInner, bool) {
	if o == nil || IsNil(o.HiddenFields) {
		return nil, false
	}
	return o.HiddenFields, true
}

// HasHiddenFields returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasHiddenFields() bool {
	if o != nil && !IsNil(o.HiddenFields) {
		return true
	}

	return false
}

// SetHiddenFields gets a reference to the given []GenericRemoteResponseHiddenFieldsInner and assigns it to the HiddenFields field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetHiddenFields(v []GenericRemoteResponseHiddenFieldsInner) {
	o.HiddenFields = v
}

// GetCaCert returns the CaCert field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetCaCert() string {
	if o == nil || IsNil(o.CaCert) {
		var ret string
		return ret
	}
	return *o.CaCert
}

// GetCaCertOk returns a tuple with the CaCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetCaCertOk() (*string, bool) {
	if o == nil || IsNil(o.CaCert) {
		return nil, false
	}
	return o.CaCert, true
}

// HasCaCert returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasCaCert() bool {
	if o != nil && !IsNil(o.CaCert) {
		return true
	}

	return false
}

// SetCaCert gets a reference to the given string and assigns it to the CaCert field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetCaCert(v string) {
	o.CaCert = &v
}

// GetClientCert returns the ClientCert field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetClientCert() string {
	if o == nil || IsNil(o.ClientCert) {
		var ret string
		return ret
	}
	return *o.ClientCert
}

// GetClientCertOk returns a tuple with the ClientCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetClientCertOk() (*string, bool) {
	if o == nil || IsNil(o.ClientCert) {
		return nil, false
	}
	return o.ClientCert, true
}

// HasClientCert returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasClientCert() bool {
	if o != nil && !IsNil(o.ClientCert) {
		return true
	}

	return false
}

// SetClientCert gets a reference to the given string and assigns it to the ClientCert field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetClientCert(v string) {
	o.ClientCert = &v
}

// GetTlsValidation returns the TlsValidation field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetTlsValidation() bool {
	if o == nil || IsNil(o.TlsValidation) {
		var ret bool
		return ret
	}
	return *o.TlsValidation
}

// GetTlsValidationOk returns a tuple with the TlsValidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetTlsValidationOk() (*bool, bool) {
	if o == nil || IsNil(o.TlsValidation) {
		return nil, false
	}
	return o.TlsValidation, true
}

// HasTlsValidation returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasTlsValidation() bool {
	if o != nil && !IsNil(o.TlsValidation) {
		return true
	}

	return false
}

// SetTlsValidation gets a reference to the given bool and assigns it to the TlsValidation field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetTlsValidation(v bool) {
	o.TlsValidation = &v
}

// GetProxyUrl returns the ProxyUrl field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetProxyUrl() string {
	if o == nil || IsNil(o.ProxyUrl) {
		var ret string
		return ret
	}
	return *o.ProxyUrl
}

// GetProxyUrlOk returns a tuple with the ProxyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetProxyUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyUrl) {
		return nil, false
	}
	return o.ProxyUrl, true
}

// HasProxyUrl returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasProxyUrl() bool {
	if o != nil && !IsNil(o.ProxyUrl) {
		return true
	}

	return false
}

// SetProxyUrl gets a reference to the given string and assigns it to the ProxyUrl field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetProxyUrl(v string) {
	o.ProxyUrl = &v
}

// GetMaxRetries returns the MaxRetries field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetMaxRetries() int64 {
	if o == nil || IsNil(o.MaxRetries) {
		var ret int64
		return ret
	}
	return *o.MaxRetries
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetMaxRetriesOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxRetries) {
		return nil, false
	}
	return o.MaxRetries, true
}

// HasMaxRetries returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasMaxRetries() bool {
	if o != nil && !IsNil(o.MaxRetries) {
		return true
	}

	return false
}

// SetMaxRetries gets a reference to the given int64 and assigns it to the MaxRetries field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetMaxRetries(v int64) {
	o.MaxRetries = &v
}

// GetTotalTimeout returns the TotalTimeout field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetTotalTimeout() float64 {
	if o == nil || IsNil(o.TotalTimeout) {
		var ret float64
		return ret
	}
	return *o.TotalTimeout
}

// GetTotalTimeoutOk returns a tuple with the TotalTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetTotalTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalTimeout) {
		return nil, false
	}
	return o.TotalTimeout, true
}

// HasTotalTimeout returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasTotalTimeout() bool {
	if o != nil && !IsNil(o.TotalTimeout) {
		return true
	}

	return false
}

// SetTotalTimeout gets a reference to the given float64 and assigns it to the TotalTimeout field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetTotalTimeout(v float64) {
	o.TotalTimeout = &v
}

// GetConnectTimeout returns the ConnectTimeout field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetConnectTimeout() float64 {
	if o == nil || IsNil(o.ConnectTimeout) {
		var ret float64
		return ret
	}
	return *o.ConnectTimeout
}

// GetConnectTimeoutOk returns a tuple with the ConnectTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetConnectTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.ConnectTimeout) {
		return nil, false
	}
	return o.ConnectTimeout, true
}

// HasConnectTimeout returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasConnectTimeout() bool {
	if o != nil && !IsNil(o.ConnectTimeout) {
		return true
	}

	return false
}

// SetConnectTimeout gets a reference to the given float64 and assigns it to the ConnectTimeout field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetConnectTimeout(v float64) {
	o.ConnectTimeout = &v
}

// GetSockConnectTimeout returns the SockConnectTimeout field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetSockConnectTimeout() float64 {
	if o == nil || IsNil(o.SockConnectTimeout) {
		var ret float64
		return ret
	}
	return *o.SockConnectTimeout
}

// GetSockConnectTimeoutOk returns a tuple with the SockConnectTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetSockConnectTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.SockConnectTimeout) {
		return nil, false
	}
	return o.SockConnectTimeout, true
}

// HasSockConnectTimeout returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasSockConnectTimeout() bool {
	if o != nil && !IsNil(o.SockConnectTimeout) {
		return true
	}

	return false
}

// SetSockConnectTimeout gets a reference to the given float64 and assigns it to the SockConnectTimeout field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetSockConnectTimeout(v float64) {
	o.SockConnectTimeout = &v
}

// GetSockReadTimeout returns the SockReadTimeout field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetSockReadTimeout() float64 {
	if o == nil || IsNil(o.SockReadTimeout) {
		var ret float64
		return ret
	}
	return *o.SockReadTimeout
}

// GetSockReadTimeoutOk returns a tuple with the SockReadTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetSockReadTimeoutOk() (*float64, bool) {
	if o == nil || IsNil(o.SockReadTimeout) {
		return nil, false
	}
	return o.SockReadTimeout, true
}

// HasSockReadTimeout returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasSockReadTimeout() bool {
	if o != nil && !IsNil(o.SockReadTimeout) {
		return true
	}

	return false
}

// SetSockReadTimeout gets a reference to the given float64 and assigns it to the SockReadTimeout field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetSockReadTimeout(v float64) {
	o.SockReadTimeout = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetHeaders() []map[string]interface{} {
	if o == nil || IsNil(o.Headers) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetHeadersOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []map[string]interface{} and assigns it to the Headers field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetHeaders(v []map[string]interface{}) {
	o.Headers = v
}

// GetDownloadConcurrency returns the DownloadConcurrency field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetDownloadConcurrency() int64 {
	if o == nil || IsNil(o.DownloadConcurrency) {
		var ret int64
		return ret
	}
	return *o.DownloadConcurrency
}

// GetDownloadConcurrencyOk returns a tuple with the DownloadConcurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetDownloadConcurrencyOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadConcurrency) {
		return nil, false
	}
	return o.DownloadConcurrency, true
}

// HasDownloadConcurrency returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasDownloadConcurrency() bool {
	if o != nil && !IsNil(o.DownloadConcurrency) {
		return true
	}

	return false
}

// SetDownloadConcurrency gets a reference to the given int64 and assigns it to the DownloadConcurrency field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetDownloadConcurrency(v int64) {
	o.DownloadConcurrency = &v
}

// GetRateLimit returns the RateLimit field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetRateLimit() int64 {
	if o == nil || IsNil(o.RateLimit) {
		var ret int64
		return ret
	}
	return *o.RateLimit
}

// GetRateLimitOk returns a tuple with the RateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetRateLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.RateLimit) {
		return nil, false
	}
	return o.RateLimit, true
}

// HasRateLimit returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasRateLimit() bool {
	if o != nil && !IsNil(o.RateLimit) {
		return true
	}

	return false
}

// SetRateLimit gets a reference to the given int64 and assigns it to the RateLimit field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetRateLimit(v int64) {
	o.RateLimit = &v
}

// GetHfHubUrl returns the HfHubUrl field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetHfHubUrl() string {
	if o == nil || IsNil(o.HfHubUrl) {
		var ret string
		return ret
	}
	return *o.HfHubUrl
}

// GetHfHubUrlOk returns a tuple with the HfHubUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetHfHubUrlOk() (*string, bool) {
	if o == nil || IsNil(o.HfHubUrl) {
		return nil, false
	}
	return o.HfHubUrl, true
}

// HasHfHubUrl returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasHfHubUrl() bool {
	if o != nil && !IsNil(o.HfHubUrl) {
		return true
	}

	return false
}

// SetHfHubUrl gets a reference to the given string and assigns it to the HfHubUrl field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetHfHubUrl(v string) {
	o.HfHubUrl = &v
}

// GetHfToken returns the HfToken field value if set, zero value otherwise.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetHfToken() string {
	if o == nil || IsNil(o.HfToken) {
		var ret string
		return ret
	}
	return *o.HfToken
}

// GetHfTokenOk returns a tuple with the HfToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) GetHfTokenOk() (*string, bool) {
	if o == nil || IsNil(o.HfToken) {
		return nil, false
	}
	return o.HfToken, true
}

// HasHfToken returns a boolean if a field has been set.
func (o *HuggingFaceHuggingFaceRemoteResponse) HasHfToken() bool {
	if o != nil && !IsNil(o.HfToken) {
		return true
	}

	return false
}

// SetHfToken gets a reference to the given string and assigns it to the HfToken field.
func (o *HuggingFaceHuggingFaceRemoteResponse) SetHfToken(v string) {
	o.HfToken = &v
}

func (o HuggingFaceHuggingFaceRemoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HuggingFaceHuggingFaceRemoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpHref) {
		toSerialize["pulp_href"] = o.PulpHref
	}
	if !IsNil(o.Prn) {
		toSerialize["prn"] = o.Prn
	}
	if !IsNil(o.PulpCreated) {
		toSerialize["pulp_created"] = o.PulpCreated
	}
	if !IsNil(o.PulpLastUpdated) {
		toSerialize["pulp_last_updated"] = o.PulpLastUpdated
	}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.HiddenFields) {
		toSerialize["hidden_fields"] = o.HiddenFields
	}
	if !IsNil(o.CaCert) {
		toSerialize["ca_cert"] = o.CaCert
	}
	if !IsNil(o.ClientCert) {
		toSerialize["client_cert"] = o.ClientCert
	}
	if !IsNil(o.TlsValidation) {
		toSerialize["tls_validation"] = o.TlsValidation
	}
	if !IsNil(o.ProxyUrl) {
		toSerialize["proxy_url"] = o.ProxyUrl
	}
	if !IsNil(o.MaxRetries) {
		toSerialize["max_retries"] = o.MaxRetries
	}
	if !IsNil(o.TotalTimeout) {
		toSerialize["total_timeout"] = o.TotalTimeout
	}
	if !IsNil(o.ConnectTimeout) {
		toSerialize["connect_timeout"] = o.ConnectTimeout
	}
	if !IsNil(o.SockConnectTimeout) {
		toSerialize["sock_connect_timeout"] = o.SockConnectTimeout
	}
	if !IsNil(o.SockReadTimeout) {
		toSerialize["sock_read_timeout"] = o.SockReadTimeout
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.DownloadConcurrency) {
		toSerialize["download_concurrency"] = o.DownloadConcurrency
	}
	if !IsNil(o.RateLimit) {
		toSerialize["rate_limit"] = o.RateLimit
	}
	if !IsNil(o.HfHubUrl) {
		toSerialize["hf_hub_url"] = o.HfHubUrl
	}
	if !IsNil(o.HfToken) {
		toSerialize["hf_token"] = o.HfToken
	}
	return toSerialize, nil
}

func (o *HuggingFaceHuggingFaceRemoteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHuggingFaceHuggingFaceRemoteResponse := _HuggingFaceHuggingFaceRemoteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHuggingFaceHuggingFaceRemoteResponse)

	if err != nil {
		return err
	}

	*o = HuggingFaceHuggingFaceRemoteResponse(varHuggingFaceHuggingFaceRemoteResponse)

	return err
}

type NullableHuggingFaceHuggingFaceRemoteResponse struct {
	value *HuggingFaceHuggingFaceRemoteResponse
	isSet bool
}

func (v NullableHuggingFaceHuggingFaceRemoteResponse) Get() *HuggingFaceHuggingFaceRemoteResponse {
	return v.value
}

func (v *NullableHuggingFaceHuggingFaceRemoteResponse) Set(val *HuggingFaceHuggingFaceRemoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHuggingFaceHuggingFaceRemoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHuggingFaceHuggingFaceRemoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHuggingFaceHuggingFaceRemoteResponse(val *HuggingFaceHuggingFaceRemoteResponse) *NullableHuggingFaceHuggingFaceRemoteResponse {
	return &NullableHuggingFaceHuggingFaceRemoteResponse{value: val, isSet: true}
}

func (v NullableHuggingFaceHuggingFaceRemoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHuggingFaceHuggingFaceRemoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


