/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"fmt"
)

// checks if the ContainerContainerRepository type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerContainerRepository{}

// ContainerContainerRepository Serializer for Container Repositories.
type ContainerContainerRepository struct {
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
	// A unique name for this repository.
	Name string `json:"name"`
	// An optional description.
	Description *string `json:"description,omitempty"`
	// Retain X versions of the repository. Default is null which retains all versions.
	RetainRepoVersions *int64 `json:"retain_repo_versions,omitempty"`
	// An optional remote to use by default when syncing.
	Remote *string `json:"remote,omitempty"`
	// A reference to an associated signing service.
	ManifestSigningService *string `json:"manifest_signing_service,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ContainerContainerRepository ContainerContainerRepository

// NewContainerContainerRepository instantiates a new ContainerContainerRepository object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerContainerRepository(name string) *ContainerContainerRepository {
	this := ContainerContainerRepository{}
	this.Name = name
	return &this
}

// NewContainerContainerRepositoryWithDefaults instantiates a new ContainerContainerRepository object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerContainerRepositoryWithDefaults() *ContainerContainerRepository {
	this := ContainerContainerRepository{}
	return &this
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *ContainerContainerRepository) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerRepository) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *ContainerContainerRepository) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *ContainerContainerRepository) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

// GetName returns the Name field value
func (o *ContainerContainerRepository) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContainerContainerRepository) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContainerContainerRepository) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ContainerContainerRepository) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerRepository) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ContainerContainerRepository) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ContainerContainerRepository) SetDescription(v string) {
	o.Description = &v
}

// GetRetainRepoVersions returns the RetainRepoVersions field value if set, zero value otherwise.
func (o *ContainerContainerRepository) GetRetainRepoVersions() int64 {
	if o == nil || IsNil(o.RetainRepoVersions) {
		var ret int64
		return ret
	}
	return *o.RetainRepoVersions
}

// GetRetainRepoVersionsOk returns a tuple with the RetainRepoVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerRepository) GetRetainRepoVersionsOk() (*int64, bool) {
	if o == nil || IsNil(o.RetainRepoVersions) {
		return nil, false
	}
	return o.RetainRepoVersions, true
}

// HasRetainRepoVersions returns a boolean if a field has been set.
func (o *ContainerContainerRepository) HasRetainRepoVersions() bool {
	if o != nil && !IsNil(o.RetainRepoVersions) {
		return true
	}

	return false
}

// SetRetainRepoVersions gets a reference to the given int64 and assigns it to the RetainRepoVersions field.
func (o *ContainerContainerRepository) SetRetainRepoVersions(v int64) {
	o.RetainRepoVersions = &v
}

// GetRemote returns the Remote field value if set, zero value otherwise.
func (o *ContainerContainerRepository) GetRemote() string {
	if o == nil || IsNil(o.Remote) {
		var ret string
		return ret
	}
	return *o.Remote
}

// GetRemoteOk returns a tuple with the Remote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerRepository) GetRemoteOk() (*string, bool) {
	if o == nil || IsNil(o.Remote) {
		return nil, false
	}
	return o.Remote, true
}

// HasRemote returns a boolean if a field has been set.
func (o *ContainerContainerRepository) HasRemote() bool {
	if o != nil && !IsNil(o.Remote) {
		return true
	}

	return false
}

// SetRemote gets a reference to the given string and assigns it to the Remote field.
func (o *ContainerContainerRepository) SetRemote(v string) {
	o.Remote = &v
}

// GetManifestSigningService returns the ManifestSigningService field value if set, zero value otherwise.
func (o *ContainerContainerRepository) GetManifestSigningService() string {
	if o == nil || IsNil(o.ManifestSigningService) {
		var ret string
		return ret
	}
	return *o.ManifestSigningService
}

// GetManifestSigningServiceOk returns a tuple with the ManifestSigningService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerContainerRepository) GetManifestSigningServiceOk() (*string, bool) {
	if o == nil || IsNil(o.ManifestSigningService) {
		return nil, false
	}
	return o.ManifestSigningService, true
}

// HasManifestSigningService returns a boolean if a field has been set.
func (o *ContainerContainerRepository) HasManifestSigningService() bool {
	if o != nil && !IsNil(o.ManifestSigningService) {
		return true
	}

	return false
}

// SetManifestSigningService gets a reference to the given string and assigns it to the ManifestSigningService field.
func (o *ContainerContainerRepository) SetManifestSigningService(v string) {
	o.ManifestSigningService = &v
}

func (o ContainerContainerRepository) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerContainerRepository) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RetainRepoVersions) {
		toSerialize["retain_repo_versions"] = o.RetainRepoVersions
	}
	if !IsNil(o.Remote) {
		toSerialize["remote"] = o.Remote
	}
	if !IsNil(o.ManifestSigningService) {
		toSerialize["manifest_signing_service"] = o.ManifestSigningService
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContainerContainerRepository) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerContainerRepository := _ContainerContainerRepository{}

	err = json.Unmarshal(data, &varContainerContainerRepository)

	if err != nil {
		return err
	}

	*o = ContainerContainerRepository(varContainerContainerRepository)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "retain_repo_versions")
		delete(additionalProperties, "remote")
		delete(additionalProperties, "manifest_signing_service")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContainerContainerRepository struct {
	value *ContainerContainerRepository
	isSet bool
}

func (v NullableContainerContainerRepository) Get() *ContainerContainerRepository {
	return v.value
}

func (v *NullableContainerContainerRepository) Set(val *ContainerContainerRepository) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerContainerRepository) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerContainerRepository) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerContainerRepository(val *ContainerContainerRepository) *NullableContainerContainerRepository {
	return &NullableContainerContainerRepository{value: val, isSet: true}
}

func (v NullableContainerContainerRepository) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerContainerRepository) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


